lib/features/modeling/BpmnFactory.js
lib/features/modeling/BpmnUpdater.js
lib/features/modeling/ElementFactory.js
lib/features/modeling/Modeling.js
lib/features/modeling/behavior/CreateBehavior.js
lib/features/modeling/behavior/DropBehavior.js
lib/features/modeling/behavior/RemoveBehavior.js
lib/features/modeling/behavior/index.js
lib/features/modeling/cmd/UpdateCanvasRootHandler.js
lib/features/modeling/rules/ModelingRules.js
lib/features/palette/PaletteProvider.js
test/fixtures/bpmn/collaboration/collaboration-empty-participant.bpmn
test/fixtures/bpmn/collaboration/collaboration-message-flows.bpmn
test/fixtures/bpmn/collaboration/collaboration-participant.bpmn
test/fixtures/bpmn/collaboration/process-empty.bpmn
test/fixtures/bpmn/collaboration/process.bpmn
test/spec/features/modeling/CreateParticipantSpec.js
test/spec/features/modeling/DeleteParticipantSpec.js
test/spec/features/palette/PaletteProviderSpec.js

This commit adds the ability to model participants from the palette.
* Empty diagrams can be used as a start for participant _AND_ process diagram
* Process diagrams can be converted to collaboration diagrams by dropping
a participant onto them
Closes #128

feat(modeling): add participant modeling behavior

---

lib/Modeler.js
lib/features/modeling/behavior/CreateBehavior.js
lib/features/snapping/BpmnSnapping.js
lib/features/snapping/index.js
test/spec/features/snapping/BpmnSnappingSpec.js

This PR builds on top of #240 and adds snapping of the initial participant to existing diagram content.
Closes #241

Add participant snapping

---

lib/Modeler.js
lib/Viewer.js
test/helper/index.js
test/spec/ModelerSpec.js
test/spec/ViewerSpec.js

This feature builds on top of #493 and makes the `Viewer` and `Modeler` sub-classes of `Diagram`.
Making that change provides us with a number of benefits:
* simplifies event handling
* allows diagram services to be re-used across imports
* allows diagram services to be injected (or retrieved)
before import
The implementation relies on Diagram#clear to reset the diagram before successive imports (bpmn-io/diagram-js#151).
Closes #237
__This may be a BREAKING CHANGE for people relying on BpmnJS member access__.

Make BpmnJS (Viewer/Modeler) an instance of Diagram

---

lib/Modeler.js
lib/Viewer.js
lib/import/Importer.js
test/helper/index.js
test/spec/ModelerSpec.js
test/spec/ViewerSpec.js
test/spec/import/ImporterSpec.js

This builds on top of #495 and makes sure that users of bpmn-js can hook up to diagram import via events:
* makes `#importXML` callback optional
* emit well defined events during import:
```
* import.parse.start
* import.parse.complete
* import.render.start
* import.render.complete
* import.done
```
__This is a BREAKING CHANGE__.

Allow to hook up with diagram import via events

---

lib/features/popup-menu/ReplaceMenuProvider.js
test/spec/features/popup-menu/ReplaceMenuProvider.defaultFlowsFromComplexGateways.bpmn
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

The [BPMN 2.0 specification](http://www.omg.org/spec/BPMN/2.0/) states "a Sequence Flow that has an
Exclusive, Inclusive or Complex Gateway or an Activity as its source
can also be defined with as default."
This commit will honor that statement by allowing sequence flows from
Complex Gateway to be defined as default.

fix(replace):ComplexGateway can have default sequence flows

---

lib/Viewer.js
test/spec/ViewerSpec.js

This makes the viewer emit events during SVG and XML export.
These events allow others to hook in, i.e. to trigger additional _save_
actions.
Closes #811

feat(viewer): emit export events

---

lib/draw/TextRenderer.js

This solves diagram export and rendering issues.
The font can still be easily overriden if integrators
wish to do so.
Closes #819

fix(draw): revert to Arial as default font

---

lib/features/modeling/BpmnLayouter.js
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.boundaryEvents.bpmn
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js

Depends on https://github.com/bpmn-io/diagram-js/pull/269
* use new configuration options (t|r|b|l) when laying out connection connecting boundary event
* make sure connection is laid out in a way that it will not be behind host of boundary event

Handle boundary events when laying out connection

---

lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js
package.json
test/spec/features/modeling/MoveShapeSpec.js
test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehavior.bpmn
test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehaviorSpec.js

This brings back adaptive label position on label creation.
Closes #825
Depends on https://github.com/bpmn-io/diagram-js/pull/268 for an [additional fix](https://github.com/bpmn-io/bpmn-js/commit/15596ef97cb6a2ba71817197bf1c11ce4800eaab).

Fix adaptive label positioning

---

lib/features/modeling/BpmnLayouter.js
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.boundaryEvents.bpmn
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js

Depends on https://github.com/bpmn-io/diagram-js/pull/269
* use new configuration options (t|r|b|l) when laying out connection connecting boundary event
* make sure connection is laid out in a way that it will not be behind host of boundary event

fix(bpmn-layouter): handle boundary events

---

lib/features/context-pad/ContextPadProvider.js

Improves the tooltip titles for the different IntermediateCatchEvent types
Closes https://github.com/camunda/camunda-modeler/issues/917

feat(contextPad): improve tooltip titles for IntermediateCatchEvents

---

lib/features/modeling/behavior/ConnectEventBasedGatewayBehavior.js
lib/features/modeling/behavior/index.js
lib/features/rules/BpmnRules.js
test/spec/features/modeling/behavior/ConnectEventBasedGatewayBehavior.bpmn
test/spec/features/modeling/behavior/ConnectEventBasedGatewayBehaviorSpec.js
test/spec/features/rules/BpmnRulesSpec.js

Implemented a Bpmn rule that it shouldn't be possible to attach a BoundaryEvent on a ReceiveTask following a  EventBasedGateway in two different ways:
- It isn't possible to attach a BoundaryEvent on a ReceiveTask which is already connected after a EventBasedGateway (BpmnRule)
- Deletion of attached BoundaryEvent after connecting a EventBasedGateway to a ReceiveTask (Behavior)
Closes https://github.com/camunda/camunda-modeler/issues/784

784 no boundary event after event based gateway

---

rollup.config.js

I found the date in license is error, because of Date.prototype.getDay() method returns the day of the week, and Date.prototype.getDate() method returns the day of the month which is right here.

fix: error date in license

---

lib/.eslintrc
package.json

This ensures we don't accidently require files in the lib directory
via the global `lib` import. That stuff works during tests but does
not work in the final bundle.
Considerations: This plugin adds some runtime overhead to our linting
process.
Related to https://github.com/bpmn-io/diagram-js/pull/292.

chore(project): detect unresolved lint rules

---

lib/Modeler.js
test/spec/ModelerSpec.js

This fixes the missing paste-functionality by adding the correct `BpmnCopyPaste` module.
Also adds a regression test for this kind of bug.
Fixes #900

fix(Modeler): use correct copy-paste-module

---

lib/features/ordering/BpmnOrderingProvider.js
test/spec/features/copy-paste/BpmnCopyPasteSpec.js
test/spec/features/ordering/BpmnOrderingProviderSpec.js
test/spec/features/ordering/Helper.js
test/spec/features/ordering/ordering.bpmn

This fixes the issue that labels are not properly rendered on top, resulting in funny effects like the following:
__Label Behind Participant__
__Label Removed with previous parent__

fix(ordering): render labels always on top

---

CHANGELOG.md

__Which issue does this PR address?_
https://github.com/bpmn-io/bpmn-js/issues/763
The v3.2.3 release note was not explicitly mentioned.

fix(changelog): add missing v3.2.3 release note

---

lib/import/BpmnTreeWalker.js
test/fixtures/bpmn/import/data-store.outside-participant.dangling.bpmn
test/spec/import/ImporterSpec.js

Previously, we wouldn't pass context to `contextual` which didn't make any sense. This was created as part of https://github.com/bpmn-io/bpmn-js/pull/967 or `bpmn-js/select-diagram`.

fix(BpmnTreeWalker): pass context to unhandled process handler

---

lib/features/replace/BpmnReplace.js
test/spec/features/replace/BpmnReplaceSpec.js

__Which issue does this PR address?_
Closes camunda/camunda-modeler#1210

Adjust height of pool when toggling collapse/expand button

---

lib/Modeler.js
lib/features/auto-resize/BpmnAutoResize.js
lib/features/grid-snapping/BpmnGridSnapping.js
lib/features/grid-snapping/index.js
lib/features/modeling/behavior/ToggleElementCollapseBehaviour.js
test/spec/features/grid-snapping/BpmnGridSnapping.bpmn
test/spec/features/grid-snapping/BpmnGridSnappingSpec.js

* snap resizable elements top-left
* integrate auto resize
Depends on bpmn-io/diagram-js#319
Related to camunda/camunda-modeler#1344
Related to camunda/camunda-modeler#1348
Related to camunda/camunda-modeler#1349

1344 Integrate Grid Snapping - Part 1

---

lib/features/modeling/ElementFactory.js
test/spec/features/grid-snapping/BpmnGridSnappingSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

This is a follow up to https://github.com/bpmn-io/bpmn-js/pull/975.
It sets the default height of collapsed pools to `60px` to better align with the behavior of other tools.

feat(modeling): adjust default collapsed participant height to 60px

---

lib/features/modeling/ElementFactory.js
lib/features/ordering/BpmnOrderingProvider.js
lib/features/rules/BpmnRules.js
test/fixtures/bpmn/simple-resizable.bpmn
test/spec/features/modeling/ResizeShapeSpec.js
test/spec/features/ordering/BpmnOrderingProviderSpec.js
test/spec/features/ordering/groups.bpmn
test/spec/features/rules/BpmnRules.groups.bpmn
test/spec/features/rules/BpmnRulesSpec.js
test/spec/import/elements/Groups.bpmn
test/spec/import/elements/GroupsSpec.js

This pull request aims to handle `bpmn:Group` elements as frame elements (cf. [new diagram frame feature](https://github.com/bpmn-io/diagram-js/commit/f61579b19a5a125cf0a7eaa92e65c2301e524d4c)) + add basic support for modeling operations (e.g. resizing)
Done by this PR:
* set `isFrame` property to groups on creation 
* Closes #959 
* Closes #960 
* allow groups to be resizable
* Closes #956 
* always draw groups on top
* Closes #979

Group-Frame support

---

lib/features/modeling/behavior/EventBasedGatewayBehavior.js
lib/features/modeling/behavior/SubProcessBehavior.js
lib/features/modeling/behavior/ToggleElementCollapseBehaviour.js
lib/features/modeling/behavior/index.js
test/spec/features/modeling/behavior/SubProcessBehavior.bpmn
test/spec/features/modeling/behavior/SubProcessBehaviorSpec.js

_Which issue does this PR address?_
Relates to camunda/camunda-modeler#1244
_Description_
This covers two scenarios:
1. When a shape is replaced with an expanded subprocess
2. When a subprocess is toggled from collapsed to expanded
Only when:
1. There are incoming sequence flows (previous content)
2. There are no outgoing sequence flows (following content)
_Notes for reviewer_
1. The connection layout breaks when replacing/toggling, as shown in the screen captures above. This is a [known issue](https://github.com/bpmn-io/bpmn-js/issues/1019).
2. The CI fails on codecoverage due to missing tests for [this](https://github.com/bpmn-io/bpmn-js/pull/1026/files#diff-1fa6a132a359cb077dd93245cbcdbcd2R50) and [this](https://github.com/bpmn-io/bpmn-js/pull/1026/files#diff-1fa6a132a359cb077dd93245cbc …

Prevent expanded subprocess overlap of previous content

---

lib/features/copy-paste/BpmnCopyPaste.js
test/fixtures/bpmn/features/copy-paste/properties.bpmn
test/spec/features/copy-paste/BpmnCopyPasteSpec.js

This enables copying `categoryValueRef` attributes from `bpmn:Group` elements. Per default, [references will not be copied](https://github.com/bpmn-io/bpmn-js/blob/master/lib/util/model/ModelCloneHelper.js#L72). However, in this case, it makes sense to do so.
Closes #958

fix(copy-paste): adjust categoryValueRef when group is copied

---

lib/features/modeling/BpmnFactory.js
lib/features/modeling/ElementFactory.js
lib/features/modeling/behavior/GroupBehavior.js
lib/features/modeling/behavior/index.js
lib/features/palette/PaletteProvider.js
package-lock.json
package.json
test/spec/features/modeling/behavior/GroupBehaviorSpec.bpmn
test/spec/features/modeling/behavior/GroupBehaviorSpec.js
test/spec/features/palette/PaletteProviderSpec.js

This pull request adds a new entry inside the `Palette` for creating `bpmn:Group` elements. 
Closes #954 
* Additionally, it adds a modeling behavior to automatically create an associated `bpmn:Category` + `bpmn:CategoryValue` to `bpmn:Definitions`
* It also does cleanup
* When a `bpmn:Group` is deleted, the referenced `bpmn:CategoryValue` is removed from the parent `bpmn:Category`
* When the `bpmn:Category` is empty after cleanup, it will be removed from `bpmn:Definitions` itself
This relates to an update of the `bpmn-font` library, cf. https://github.com/bpmn-io/bpmn-font/issues/15

Add group palette action

---

lib/features/grid-snapping/behavior/LayoutConnectionBehavior.js

Requires https://github.com/bpmn-io/diagram-js/pull/345

fix(grid-snapping): use correct align values for segment snapping

---

lib/draw/BpmnRenderer.js
lib/features/label-editing/LabelEditingProvider.js
lib/features/label-editing/LabelUtil.js
lib/features/label-editing/cmd/UpdateLabelHandler.js
lib/features/modeling/behavior/GroupBehavior.js
lib/features/modeling/behavior/util/CategoryUtil.js
lib/features/rules/BpmnRules.js
lib/import/BpmnImporter.js
lib/util/LabelUtil.js
test/spec/draw/BpmnRendererSpec.js
test/spec/features/label-editing/LabelEditing.bpmn
test/spec/features/label-editing/LabelEditingProviderSpec.js
test/spec/features/modeling/UpdateLabel.bpmn
test/spec/features/modeling/UpdateLabelSpec.js

Closes #955 
* Moves Category + Value creation to separate util, cf. ed45a22
* Enables label editing for `bpmn:Group` elements  (via external label), cf. 0217a87
* Creates missing `bpmn:CategoryValue` when not existing, cf. a61609a

Group direct editing

---

lib/features/ordering/BpmnOrderingProvider.js
lib/features/snapping/BpmnSnapping.js
test/fixtures/bpmn/collaboration/process.bpmn
test/spec/features/modeling/behavior/CreateParticipantBehaviorSpec.js
test/spec/features/ordering/BpmnOrderingProviderSpec.js
test/spec/features/ordering/groups.bpmn
test/spec/features/ordering/ordering.bpmn
test/spec/features/snapping/BpmnSnappingSpec.js

Closes #1043 
* Always render `bpmn:Group` elements on collaboration level, cf. a966ec3
* Prevent participants snap to group bounds, cf. c6670039e48e3ccf10c2976fc20d43b48de412aa
Note: Unmerged changes in https://github.com/bpmn-io/bpmn-js/pull/1046 refactor the participant-snapping to another place. After merge, the changes in c6670039e48e3ccf10c2976fc20d43b48de412aa should be moved as well.

Prevent participant resizing on group interaction

---

lib/features/modeling/behavior/SubProcessStartEventBehavior.js
lib/features/modeling/behavior/index.js
test/spec/features/modeling/behavior/SubProcessBehavior.start-event.bpmn
test/spec/features/modeling/behavior/SubProcessStartEventBehaviorSpec.js

_Which issue does this PR address?_
Related to camunda/camunda-modeler#1242
Dependent on bpmn-io/diagram-js#347
This automatically adds a start event to an expanded subprocess when:
1. Creating an expanded subprocess from the palette.
2. Replacing a task with an expanded subprocess.

Add subprocess with start event included

---

lib/features/modeling/behavior/AttachEventBehavior.js
lib/features/modeling/behavior/index.js
lib/features/replace/BpmnReplace.js
lib/features/rules/BpmnRules.js
test/fixtures/bpmn/boundary-events.bpmn
test/spec/features/modeling/behavior/AttachEventBehaviorSpec.js
test/spec/features/modeling/layout/LayoutConnectionSpec.js
test/spec/features/replace/BpmnReplaceSpec.js
test/spec/features/rules/BpmnRules.attaching.bpmn
test/spec/features/rules/BpmnRulesSpec.js

Closes #478
Builds on top of and includes changes in https://github.com/bpmn-io/bpmn-js/pull/1047
Requires https://github.com/bpmn-io/diagram-js/pull/354

Allow to change intermediate events to boundary events

---

test/spec/features/modeling/layout/LayoutConnectionSpec.js

This disables an integration test for connection preview when dragging a new element. The test will fail once https://github.com/bpmn-io/diagram-js/pull/355 is merged.

Disable connection preview test for dragged new element

---

lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js
test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehavior.boundary-events.bpmn
test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehaviorSpec.js

* Do not allow placing label onto host
Relates to camunda/camunda-modeler#1206

feat(modeling): improve label positioning for boundary events

---

lib/features/modeling/BpmnLayouter.js
lib/features/snapping/BpmnConnectSnapping.js
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.boundaryEventsLoops.bpmn
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js
test/spec/features/snapping/BpmnConnectSnapping.bpmn
test/spec/features/snapping/BpmnConnectSnappingSpec.js

Summary of changes:
* we no longer snap to target center during connection
* we snap inside of the target element
* we snap Boundary Event loops in the way to make sure the connection end is not too close
* layouter checks the area where cursor is placed to determine loop layout hints
Required by https://github.com/camunda/camunda-modeler/issues/903
See screenshots in the linked issue for the context.

Correctly lay out boundary to activity loops

---

lib/features/replace-preview/BpmnReplacePreview.js
lib/features/rules/BpmnRules.js
test/spec/features/rules/BpmnRules.collaboration.bpmn
test/spec/features/rules/BpmnRulesSpec.js

Removes the `new-parent` overlay when hovering label over elements. Allows to set `canExecute` for `elements.move` to `null` in a general manner (cf. https://github.com/bpmn-io/diagram-js/pull/357)
Closes #1054 
Depends on https://github.com/bpmn-io/diagram-js/pull/357.

Allow visually ignored movements

---

lib/features/snapping/BpmnConnectSnapping.js
test/spec/features/modeling/MoveElements.centered-connection.bpmn
test/spec/features/modeling/MoveElementsSpec.js
test/spec/features/snapping/BpmnConnectSnapping.bpmn
test/spec/features/snapping/BpmnConnectSnappingSpec.js

This brings center-snap on connecting back for certain scenarios:
* When connecting to `bpmn:Event` or `bpmn:Gateway` (cf. #1079)
* When connecting to `bpmn:Task` center area (cf. #1086) 
Closes #1079 
Closes #1086 
Look & Feel:

brings center-snap back to glory

---

lib/features/rules/BpmnRules.js
test/spec/features/rules/BpmnRulesSpec.js

Closes https://github.com/bpmn-io/bpmn-js/issues/1095

Allow to drop Boundary Events only on containers

---

lib/features/context-pad/ContextPadProvider.js
lib/features/palette/PaletteProvider.js

When I use translations there are some tooltips on my pallet that are still in English like `StartEvent`, `EndEvent` or `Task`.
It's a little bit weird because the phrase begins in my language and ends in other language.
The reason for that is because there is a generic keyword `Create {type}`.
I'm suggesting create specific keywords for these cases.

feat(translations): add new keywords

---

lib/Modeler.js
lib/features/interaction-events/BpmnInteractionEvents.js
lib/features/interaction-events/index.js
lib/features/modeling/behavior/FixHoverBehavior.js
package-lock.json
package.json
test/spec/features/interaction-events/BpmnInteractionEventsSpec.js
test/spec/features/modeling/behavior/FixHoverBehaviorSpec.js

Related https://github.com/camunda/camunda-modeler/issues/238
Requires https://github.com/bpmn-io/diagram-js/pull/371
Closes https://github.com/bpmn-io/bpmn-js/issues/957

Improve navigation inside large participants

---

lib/draw/BpmnRenderer.js
test/fixtures/bpmn/draw/events.bpmn

This PR resolve the issue #1090.

Multiple and parallel multiple events

---

lib/features/snapping/BpmnCreateMoveSnapping.js
test/spec/features/snapping/BpmnCreateMoveSnapping.trbl-snapping.bpmn
test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js

Depends on https://github.com/bpmn-io/diagram-js/pull/376
Closes #1104

Add TRBL snapping against containers only

---

lib/features/copy-paste/BpmnCopyPaste.js
lib/features/modeling/behavior/GroupBehavior.js
lib/features/modeling/behavior/LabelBehavior.js
test/spec/features/copy-paste/BpmnCopyPasteSpec.js
test/spec/features/modeling/behavior/GroupBehaviorSpec.js
test/spec/features/modeling/behavior/LabelBehaviorSpec.js

This fixes the broken copy & paste behavior for `bpmn:Group` elements (cf. camunda/camunda-modeler#1417) by
* Creating a new `bpmn:CategoryValue` for every pasted `bpmn:Group` element
* Sets the copied name value to newly created category value
* Ensures `LabelBehavior` is not restricted to `name` attribute but retrieves label value via `LabelUtil#getLabel`
Closes camunda/camunda-modeler#1417
**Note:** Beginning with these changes we do not allow creating `bpmn:Group` elements with same referenced `bpmn:CategoryValue` via our modeling tools. However, #1055 is not completely fixed for diagrams which include groups with same referenced category values (e.g. from other editors). Let's tackle this at another place somewhat in the future, especially when we create a strategy to link and unlink …

Copy & Paste Behavior for Group elements

---

lib/features/rules/BpmnRules.js
test/spec/features/rules/BpmnRulesSpec.js
test/spec/features/rules/Helper.js

> This fixes a wrong rule that allows an illegal operation, blowing up the editor 💥 💨.
> 
> ![capture sK6UQI_optimized](https://user-images.githubusercontent.com/58601/61628469-b42bb500-ac82-11e9-84f4-258d0add1b4b.gif)
> 
> Required by [camunda/camunda-modeler#1431](https://github.com/camunda/camunda-modeler/issues/1431)
Author: @nikku

fix(rules): disallow dropping on labels and groups

---

lib/features/modeling/behavior/CreateParticipantBehavior.js
test/spec/features/modeling/behavior/CreateParticipantBehaviorSpec.js

This ensures we have left children to properly create new participant's bounds. This case of no left children after the filter operation can happen if we only have `bpmn:Group` elements in the diagram (which wouldn't make sense in practice, but however ...)
Closes #1133

fix(create-participant-behavior): ensure available children

---

lib/features/rules/BpmnRules.js
test/spec/features/rules/BpmnRulesSpec.js
test/spec/features/rules/Helper.js

* basic copy rules are implemented in diagram-js CopyPaste e.g. labels can only be copied when their label target is copied
Closes #1153

fix(rules): always allow copying labels

---

lib/features/palette/PaletteProvider.js
test/spec/features/palette/PaletteProviderSpec.js

Only selects start event after creating sub process through specifying `autoSelect`.
Depends on https://github.com/bpmn-io/diagram-js/pull/392
Related to #1152

Select Start Event After Creating Sub Process

---

lib/features/modeling/behavior/EventBasedGatewayBehavior.js
test/spec/features/copy-paste/BpmnCopyPasteSpec.js
test/spec/features/copy-paste/event-based-gateway.bpmn

The incoming connections of an event based gateway
target should not be removed when pasting.
Closes #1163

Repair event based gateway target pasting

---

lib/features/auto-place/AutoPlace.js
lib/features/grid-snapping/behavior/AutoPlaceBehavior.js
lib/features/label-editing/LabelEditingProvider.js
test/spec/features/auto-place/AutoPlaceSpec.js

* `autoPlace` event renamed to `autoPlace.getPosition`
Related to camunda/camunda-modeler#1502

fix(auto-place): complete direct editing on autoPlace init

---

lib/features/copy-paste/ModdleCopy.js
test/spec/features/copy-paste/ModdleCopySpec.js

Related to camunda/camunda-modeler#1507
Related to https://app.camunda.com/jira/browse/SUPPORT-6386.

fix(copy-paste): do NOT copy generic properties

---

lib/features/modeling/behavior/CreateBoundaryEventBehavior.js
lib/features/snapping/BpmnCreateMoveSnapping.js
test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js

Closes #1204
Related to https://github.com/bpmn-io/diagram-js/pull/413
This also fixes: #1205 however will do another PR for that issue to commit some tests.

fix(modeling): attach shapes with labels on paste

---

lib/features/modeling/behavior/ReplaceConnectionBehavior.js

Since there is no danger of re-selecting non-existing elements, the comment should be updated.
Requires https://github.com/bpmn-io/diagram-js/pull/422

chore(modeling): update the comment in replace connection

---

lib/features/modeling/behavior/LabelBehavior.js
test/spec/features/modeling/behavior/LabelBehavior.copyPaste.bpmn
test/spec/features/modeling/behavior/LabelBehaviorSpec.js

Related to https://github.com/zeebe-io/zeebe-modeler/issues/134

Skip label moving if label is not yet created.

---

test/config/karma.unit.js

Source maps are really helpful when debugging and don't significantly change the bundle time.

chore(project): use source maps in tests

---

lib/draw/BpmnRenderer.js
test/spec/draw/BpmnRenderer.colors.bpmn
test/spec/draw/BpmnRendererSpec.js

Only characters and numbers are allowed. Anything else will be escaped.
Closes #1209

fix(bpmn-renderer): properly escape marker ids

---

test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

This fixes the tests that depended on diagram-js Popup Menu internals. 
Requires https://github.com/bpmn-io/diagram-js/pull/431

test(popup-menu): remove dependency on internals

---

lib/features/modeling/behavior/UnclaimIdBehavior.js
test/spec/features/modeling/behavior/UnclaimIdBehaviorSpec.bpmn
test/spec/features/modeling/behavior/UnclaimIdBehaviorSpec.js

* unclaim ID of deleted shapes and connections
* unclaim ID of referenced processes when deleting participant
* this does NOT ensure we unclaim IDs of elements like DI, events, errors, ...
Related to camunda/camunda-modeler#1503
Related to #608

fix(modeling): unclaim ID on shape/connection delete

---

lib/features/modeling/BpmnLayouter.js
lib/features/modeling/BpmnUpdater.js
lib/features/modeling/behavior/BoundaryEventBehavior.js
lib/features/modeling/behavior/DataInputAssociationBehavior.js
lib/features/modeling/behavior/FixHoverBehavior.js
lib/features/modeling/behavior/ReplaceConnectionBehavior.js
lib/features/rules/BpmnRules.js
lib/features/snapping/BpmnConnectSnapping.js
test/integration/custom-elements/CustomRules.js
test/spec/features/modeling/behavior/FixHoverBehaviorSpec.js
test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

Related to https://github.com/bpmn-io/diagram-js/pull/427.

Connect Reverse

---

tasks/wiredeps

As discussed, we do not ever want to link upstream feature branches _if_ we target the `master` branch. This change implements the behavior.
This should fix https://github.com/bpmn-io/bpmn-js/pull/1240.

chore(project): do not link upstream PRs against master

---

lib/features/modeling/behavior/RootElementReferenceBehavior.js
lib/features/modeling/behavior/index.js
test/spec/features/modeling/behavior/RootElementReferenceBehavior.bpmn
test/spec/features/modeling/behavior/RootElementReferenceBehaviorSpec.js

* copy references when copying element
* add referenced root element if it doesn't exist
* do NOT add referenced root element if root element with same ID exists
* works around https://github.com/bpmn-io/bpmn-js/issues/798
Related to camunda/camunda-modeler#1049.
Related to camunda/camunda-modeler#1463.

feat(copy-paste): copy error, escalation, message and signal references

---

test/helper/index.js
test/spec/ModelerSpec.js
test/spec/NavigatedViewerSpec.js
test/spec/ViewerSpec.js

Ensure that modeler instances created outside a `bootstrapModeler` can be cleaned up like any other bpmn-js test instance.

Clean test

---

lib/features/modeling/behavior/CreateBehavior.js
test/spec/features/modeling/lanes/SplitLane.nested.bpmn
test/spec/features/modeling/lanes/SplitLaneSpec.js
test/spec/features/modeling/lanes/UpdateFlowNodeRefs.basic.bpmn
test/spec/features/modeling/lanes/UpdateFlowNodeRefsSpec.js
test/spec/features/modeling/lanes/lanes.bpmn
test/spec/features/modeling/lanes/participant-lane.bpmn
test/spec/features/modeling/lanes/participant-no-lane.bpmn

Do not adjust lane parent to participant

---

lib/features/modeling/BpmnUpdater.js
test/spec/features/modeling/BpmnUpdater.bpmn
test/spec/features/modeling/BpmnUpdaterSpec.js

Related to camunda/camunda-modeler#1611
______
Prevents connections to be cropped after pasting because it would break the layout of loops, caused by a known bug in our path intersection library, cf. https://github.com/bpmn-io/path-intersection/issues/7

fix(modeling): do not crop waypoints on pasting

---

lib/features/context-pad/ContextPadProvider.js
test/spec/features/context-pad/ContextPadProviderSpec.js

Related to camunda/camunda-modeler#1613

Do Not Open Replace Menu If Context Menu Not Open

---

lib/features/snapping/BpmnCreateMoveSnapping.js
test/spec/features/snapping/BpmnCreateMoveSnapping.docking-create-mode.bpmn
test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js

Related to: https://github.com/camunda/camunda-modeler/issues/1612
This PR:
1) Sets correctly the snap origins of docking points
2) Prevents adding not-yet-created docking points to snap target.

Fix snapping of docking points on creation mode

---

lib/features/rules/BpmnRules.js
test/spec/features/modeling/MoveElements.collaboration-association.bpmn
test/spec/features/modeling/MoveElementsSpec.js
test/spec/features/rules/BpmnRulesSpec.js

This relates to https://github.com/camunda/camunda-modeler/issues/1635.
In the past we would allow assocations between all kinds of elements. While we allow only data associations to be modeled (explicit direction), this ensures that associations, when still being present, are not removed during save (or move):

Allow associations wherever data associations are allowed, too

---

lib/features/modeling/BpmnFactory.js
test/spec/features/modeling/BpmnFactorySpec.js

This makes sure that the semantic ID prefix reflects
the common type of all replace options.
ID prefixes for elements will match the examples:
* `bpmn:ServiceTask` => `Activity_<id_suffix>`
* `bpmn:EndEvent` => `Event_<id_suffix>`
* `bpmn:EventBasedGateway` => `Gateway_<id_suffix>`
* `bpmn:SequenceFlow` => `Flow_<id_suffix>`
Related to https://github.com/camunda/camunda-modeler/issues/1654
---
Why `bpmn:ServiceTask` => `Activity_<id_suffix>`? Because we allow to morph tasks into subprocesses and call activities.

feat(modeling): create generic ids for new elements

---

lib/import/BpmnImporter.js
test/fixtures/bpmn/import/groups.bpmn
test/spec/import/ImporterSpec.js

Closes #1278
Ensures `bpmn:Group` elements got handled as frames in Viewer and NavigatedViewer.

fix(import): set <isFrame> property on import

---

lib/features/copy-paste/ModdleCopy.js
test/spec/features/copy-paste/ModdleCopySpec.js

`parent` was previously not defined.
The only reason it did not :boom: in most contexts is that there exists a global `window.parent` property that :face_with_head_bandage: things.
---
Related to https://github.com/bpmn-io/vs-code-bpmn-io/issues/65

fix(copy-paste): emit <moddleCopy.canSetCopiedProperty> with existing property

---

lib/features/label-editing/cmd/UpdateLabelHandler.js
test/spec/features/modeling/UpdateLabelSpec.js

Related to bpmn-io/diagram-js-direct-editing#12

Resize Empty Text Annotations on Complete

---

test/config/karma.distro.js
test/config/karma.unit.js

Not needed to run Chrome on Linux as of 2020.

test(project): remove legacy CI hacks

---

lib/features/di-ordering/BpmnDiOrdering.js
lib/features/di-ordering/index.js
lib/features/modeling/index.js
test/spec/features/ordering/BpmnDiOrderingSpec.js
test/spec/features/ordering/wrong-di-order.bpmn

Related to https://github.com/camunda/camunda-modeler/issues/1326
Closes #985

fix(modeling): save bpmndi as drawn on the diagram

---

lib/features/modeling/ElementFactory.js
lib/features/replace/BpmnReplace.js
lib/features/replace/ReplaceOptions.js
test/spec/features/modeling/ElementFactorySpec.js
test/spec/features/popup-menu/ReplaceMenuProvider.events.bpmn
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

Closes https://github.com/bpmn-io/bpmn-js/issues/1296

feat(replace): create bpmn:LinkEventDefinition with empty name

---

lib/features/label-editing/cmd/UpdateLabelHandler.js
test/spec/features/modeling/UpdateLabelSpec.js

This prevents a bug that cause the label target to be accidentally
resized if the user updates the label value to an empty string (or null).
Closes #1294

fix(modeling): do not resize label target when setting empty label

---

test/fixtures/bpmn/boundary-events.bpmn
test/spec/features/modeling/ResizeShapeSpec.js
test/spec/features/modeling/lanes/AddLaneSpec.js
test/spec/features/modeling/lanes/lanes-flow-nodes.bpmn

New behavior: If the attachment or connections can stay in same place after resize, keep it there.
Related to https://github.com/bpmn-io/bpmn-js/issues/1289
Related to https://github.com/camunda/camunda-modeler/issues/1737
Related to https://github.com/camunda/camunda-modeler/issues/655
Requires https://github.com/bpmn-io/diagram-js/pull/452

Improve layouting of boundary elements and connections on host/source/target resize

---

lib/features/modeling/BpmnLayouter.js
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.subProcess.bpmn

Before:
After:
Related to https://github.com/camunda/camunda-modeler/issues/1758

feat(layouter): prefer straight layout for sub-process connections

---

package-lock.json
package.json

There is no need to download it in production as we already bundle it
with the bpmn-js distribution.

chore(deps): make bpmn-font a development dependency

---

CHANGELOG.md
package-lock.json
package.json

* update CHANGELOG
* bump to diagram-js@6.6.1
Related to https://github.com/camunda/camunda-modeler/issues/1776

Prepare Release of v6.5.0

---

lib/util/CompatibilityUtil.js

This simplifies the warning text and corrects wrong spacing in the current version:

chore(util/CompatibilityUtil): correct spacing and simplify warning

---

lib/features/rules/BpmnRules.js
test/spec/features/rules/BpmnRulesSpec.js

fix(bpmnRules): disallow boundaryEvents as message flow targets

---

CHANGELOG.md
lib/features/popup-menu/ReplaceMenuProvider.js
lib/features/replace/ReplaceOptions.js
lib/features/rules/BpmnRules.js
test/fixtures/bpmn/features/replace/01_replace.bpmn
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

Closes #831 
Fix upstream https://github.com/camunda/camunda-modeler/issues/498

Disallow typed start events in sub processes

---

lib/features/rules/BpmnRules.js
test/spec/features/rules/BpmnRules.boundaryEvent.bpmn
test/spec/features/rules/BpmnRulesSpec.js

We accidentally removed the ability to have message boundary events as message flow target with https://github.com/bpmn-io/bpmn-js/issues/1300. This re-adds this capability but still disallows it for any other boundary event.
Closes #1346
Related to camunda/camunda-modeler#1919

fix(rules): allow message boundary event as message flow target

---

lib/features/popup-menu/ReplaceMenuProvider.js
lib/features/replace/BpmnReplace.js
lib/features/replace/ReplaceOptions.js
lib/util/DiUtil.js
test/fixtures/bpmn/features/replace/data-elements.bpmn
test/spec/features/context-pad/ContextPadProviderSpec.js
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

Add switch between DataStore and DataObject in replace menu

---

lib/features/popup-menu/ReplaceMenuProvider.js
lib/features/replace/ReplaceOptions.js
test/spec/features/popup-menu/ReplaceMenuProvider.pools.bpmn
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

* Indicate the action in a clearer, more standard-compliant way --> replaces an expanded pool with an empty "black box" + removing its content.
* We will not update the action identifier (`replace-with-collapsed-pool`) to avoid breaking changes.
* Make it possible to retrieve label via function
Related to camunda/camunda-modeler#2022

feat(replace-menu): update label of collapsed pool

---

docs/project/SETUP.md

This PR adds a section that documents how to execute a single test that allows to run an instance of the modeler in the browser.

Add step in setup file to run modeler in browser

---

lib/features/palette/PaletteProvider.js
test/spec/features/palette/PaletteProviderSpec.js

This prevents unwanted move events when triggered by the palette action. It fixes the issue described in #1402, when clicking the action multiple times.
Closes #1402

fix(palette): activate globalConnect tool instead of toggling

---

test/TestHelper.js
test/helper/index.js

This prevents the .test-container selector to appear twice in our test
markup:
```html
<div class="test-container passed" id="camunda-properties simple should
open stuff">
<div class="title-row">
<a href="#camunda-properties%20simple%20should%20open%20stuff">
<h3 class="test-titel">camunda-properties simple should open
stuff</h3>
</a>
<div class="test-result" style="float: right;">passed</div>
</div>
<div class="test-content-container test-container">
</div>
</div>
```
With this commit we only add the .test-content-container marker in cases
where `mocha-test-container-support` is not present upon running
`bootstrapBpmnJS`.
Closes #

test: do not double add test-container class

---

lib/features/modeling/behavior/FixHoverBehavior.js
test/spec/features/modeling/behavior/FixHoverBehaviorSpec.js

This ensures our FixHoverBehavior (that ensures we drop onto / connect to participants, not lanes) does fix the hover element during *.out, too.
Otherwise there is no way for other behaviors to correctly remove hover indicators.
We did properly handle that during connect already, just not during shape add or move :dash:.
---
Closes https://github.com/bpmn-io/bpmn-js/issues/1413

fix(modeling): if we fix hover, we gotta fix out, too

---

lib/BaseViewer.js
test/spec/ViewerSpec.js

This ensures we can safely listen to `saveXML.done` (`{ error, xml }`) to get notified on save errors, too.

Always save xml done

---

lib/features/context-pad/ContextPadProvider.js
lib/features/rules/BpmnRules.js
test/spec/features/context-pad/ContextPad.activation.bpmn
test/spec/features/context-pad/ContextPadProviderSpec.js
test/spec/features/rules/BpmnRulesSpec.js

[![Build Status](https://travis-ci.com/bpmn-io/bpmn-js.svg?branch=develop)](https://travis-ci.com/bpmn-io/bpmn-js)
🔗 linked to camunda modeler issue : https://github.com/camunda/camunda-modeler/issues/2042
purpose : enable connection tool to text annotation
modified : 
- BpmnRules.js to be able start link from annotation to other component
- ContextPafProvider.js to add connectTool in the menu in addition to the remove icon

2042 - enable connection tool for text annotation

---

lib/features/modeling/behavior/BoundaryEventBehavior.js
test/spec/features/modeling/behavior/BoundaryEvent.bpmn
test/spec/features/modeling/behavior/BoundaryEventBehaviorSpec.js

When replacing an element, references to root elements (e.g. Error, Escalation, Message, Signal) will be copied if possible.
Related to camunda/camunda-modeler#2185.

Copy Root Element References on Replace

---

lib/features/modeling/behavior/MessageFlowBehavior.js
lib/features/modeling/behavior/index.js
test/spec/features/modeling/behavior/MessageFlowBehavior.bpmn
test/spec/features/modeling/behavior/MessageFlowBehaviorSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

Reconnects message flows instead of removing them when a participant is collapsed.
---
Related to https://github.com/camunda/camunda-modeler/issues/1651.

Reconnect Message Flows When Collapsing Participant

---

lib/draw/BpmnRenderer.js
test/fixtures/bpmn/draw/message-label.bpmn
test/spec/draw/BpmnRendererSpec.js

Shows the label for referenced messages on message flows
We decided to focus on rendering the label and not make the label movable/editable at this point. The Message ref can only be added with external tools, so displaying the name is enough for now.
closes #777

feat(message): show label on message flow

---

lib/features/rules/BpmnRules.js
test/spec/features/rules/BpmnRules.process.bpmn
test/spec/features/rules/BpmnRulesSpec.js

The UX when dropping on a flow is not ideal, as it gets highlighted when hovering and then disappearing. However, this behavior is consistent with dragging complex elements on a flow.
closes #1440

fix(paste): don't insert multiple shapes on flow

---

test/helper/index.js
test/spec/helper/InjectSpec.js

This makes sure we can create async tests. Without the `return`, a test failure would end up as an unhandled Promise rejection.
So this should work in the new setup and doesn't work currently:
```js
it('should fail', inject(async function(elementRegistry) {
expect(elementRegistry).to.exist;
return Promise.reject(new Error('should fail'));
}));
```

test: support Promise as return value in `inject`

---

lib/draw/BpmnRenderUtil.js
lib/draw/BpmnRenderer.js
lib/features/copy-paste/BpmnCopyPaste.js
lib/features/modeling/cmd/SetColorHandler.js
lib/features/replace/BpmnReplace.js
package-lock.json
package.json
test/spec/draw/BpmnRenderUtilSpec.js
test/spec/draw/BpmnRenderer.colors.bpmn
test/spec/draw/BpmnRendererSpec.js
test/spec/features/copy-paste/BpmnCopyPasteSpec.js
test/spec/features/modeling/SetColorSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

Along with custom bpmn.io extension properties, `modeling#setColor` will use [BPMN in Color properties](https://github.com/bpmn-miwg/bpmn-in-color) to serialize element colors.

Use bpmn in color

---

.github/workflows/POST_RELEASE.yml
tasks/stages/await-published
tasks/stages/update-demo
tasks/stages/update-examples
tasks/stages/update-integration-test
tasks/stages/update-website

We've recently added a couple of improvements to our form-js `POST_RELEASE` build (https://github.com/bpmn-io/form-js/pull/174).
This PR ports the changes over to bpmn-js:
* Error handling like GitHub actions do it
* Fixed shebang
* Fixed `await-released` stage
* Use organization managed rather than repository managed access token

Port `POST_RELEASE` improvements over from `form-js` 

---

lib/draw/PathMap.js

The previous regex is risky as it can have exponential execution time if we nest tokens, e.g. `{{{{{{{`.
Still, it's not a vulnerability as we use only hard-coded values for strings passed to `format`.

fix(path-map): disallow nested tokens

---

rollup.config.js
tasks/build-distro.js

For a long time I was wondering why bundling got so slow, especially noticeable after `npm install`. 
With the introduction proper bundle logs (https://github.com/bpmn-io/bpmn-js/commit/3dfc1dd07e91de9575bdc6339ee76dbf614338ce) the issue got apparent: We do bundle _all_ distributions twice, in `NODE_ENV=(development,production)`.
This PR ensures we build the distribution only once:
* development is built with NODE_ENV=development
* production is built with NODE_ENV=production

chore: prevent double bundling

---

assets/bpmn-js.css

fix(drilldown): break long breadcrumbs

---

assets/bpmn-js.css
package-lock.json
package.json

Related to https://github.com/bpmn-io/diagram-js/issues/581
Requires https://github.com/bpmn-io/diagram-js/pull/583 to be merged and integrated.
This only effects the subprocess navigation features, in a minimal fashion:
_Before_
_After_

style: update used colors

---

assets/bpmn-js.css

closes #1529
**How to test**
In `test/TestHelper.js`, you can add css for the test cases:
```javascript
insertCSS('foobar.css', `
body {
line-height: 3px;
}
a {
color: green;
}
`);
```

chore(drilldown): make CSS more robust

---

assets/bpmn-js.css
lib/features/drilldown/DrilldownOverlays.js
package-lock.json
package.json
test/spec/ModelerSpec.js
test/spec/ViewerSpec.js
test/spec/features/drilldown/DrilldownSpec.js

* react to palette state
* expose own state to djs-container
related to https://github.com/bpmn-io/diagram-js/issues/591

feat(drilldown): make breadcrumbs reactive

---

assets/bpmn-js.css

Allows the use of planes in the viewer without including `diagram-js.css`

chore(css): expose color variables in bpmn-js.css

---

lib/features/modeling/behavior/DropOnFlowBehavior.js
test/spec/features/modeling/behavior/DropOnFlowBehaviorSpec.js

This tackles what has been identified as option :two: [here](https://github.com/bpmn-io/bpmn-js/issues/1541#issuecomment-984764584).
The benefit of this solution is that it is a no magic, robust one and in line with our [no surprises](https://github.com/bpmn-io/design-principles#no-surprises) design principle.
I can drop anywhere, but must also be able to handle the consequences of doing so :wink:.
---
Closes #1541

Fix drop on flow

---

lib/features/modeling/cmd/SetColorHandler.js
test/spec/features/modeling/SetColor.bpmn
test/spec/features/modeling/SetColorSpec.js

Setting colors on external labels would not set the `bpmndi:BPMNLabel#color` property but rather serialize it illegally as `bpmndi:BPMNEdge#background-color`. This PR fixes the behavior to adopt the standards compliant serialization.
Note that we already support reading color in the correct way, cf. `BpmnRenderer`.
---
Related to https://github.com/camunda/camunda-modeler/issues/2599.

fix(modeling): set label color on `bpmndi:BPMNLabel#color`

---

lib/features/palette/PaletteProvider.js
test/spec/features/palette/PaletteProviderSpec.js

The canonical modeling operation shall not be drill down, but continue to model.

feat(modeling): don't select start-event inside newly created sub-process

---

lib/features/label-editing/LabelEditingProvider.js
test/spec/features/label-editing/LabelEditingProviderSpec.js

The first canonical operation is to resize the group to the respective size, not to assign a group label.
---
Note to reviewer: In an ideal world, group creation would be implemented similar to the lasso tool. I still believe this is a substantial improvement.

feat(modeling): do not activate direct editing on newly created group

---

lib/features/modeling/ElementFactory.js
test/spec/features/modeling/ElementFactorySpec.js
test/spec/features/replace/BpmnReplaceSpec.js

With the refactoring in e1efb556f2cb7cfb92a2361b9dfa0ea96dbadebd, we broke the following scenario:
- Create a collapsed subprocess
- Try to expand it
We need to ensure the `collapsed` property is set before expanding/collapsing the shape.

fix(bpmnReplace): ensure `collapsed` is set before replacing

---

tasks/wiredeps

This extends our wiredeps skip logic to not only match `master` branches and tags but also any backport branches `\d.x` as well as PRs that target master and backport branches.
Why: Because we want to safely backport things (and fix things) without wiredeps interferring.
---
---
Proof it works: https://github.com/bpmn-io/bpmn-js/pull/1573.

chore: skip wiredeps on backport branches

---

lib/features/drilldown/DrilldownCentering.js
test/spec/features/drilldown/DrilldownIntegrationSpec.js

closes #1565
Idea here: A Collaboration is always the root, so it will have a stored Viewbox when it accessed via 'drillUp'. We can safely assume that we want to keep the viewbox otherwise.
A cleaner solution would be to introduce a `hints` Object on the `setRootElement` API and add `{keepViewbox: true}` when we replace it in:
https://github.com/bpmn-io/bpmn-js/blob/4e08a1c703e71866ef1b11d2196daa2374a618ec/lib/features/modeling/cmd/UpdateCanvasRootHandler.js#L66-L68
However, this requires some changes in diagram-js, so I decided to go for the easy fix.

fix(drilldown): don't reset vieport on `makeCollaboration`

---

lib/features/modeling/behavior/CreateParticipantBehavior.js
test/spec/features/modeling/behavior/CreateParticipantBehaviorSpec.js

* during `#preExecute` of `elements.create` process is passed to `shape.create` to be reused during `#execute` (there is no `#exeute` for `elements.create` as it only executes other commands during `#preExecute`)
* process must be reused during `#execute` of `shape.create` for `#redo` to work
* refactor implementation
Closes #1439

Reusing Process When Creating First Participant Works on Redo

---

lib/import/Importer.js
test/spec/import/ImporterSpec.js
test/spec/import/multiple-nestes-processes.bpmn

closes #1546
- When opening a diagram of a subprocess, I want to import all associated diagrams and switch to the plane I requested
- When the file has multiple overlapping DIs for the same process we are opening, only import one. If none is specified, use the first.

feat(importer): import all associated processes

---

lib/BaseViewer.js
test/spec/ViewerSpec.js

When exporting as SVG in bpmn-js@9.0.0-alpha.1, the file is empty.
This PR ensures that we export the currently visible layer in the SVG.

fix(viewer): use active plane for svg export

---

lib/features/drilldown/DrilldownBreadcrumbs.js
lib/features/modeling/behavior/SubProcessPlaneBehavior.js
test/spec/features/drilldown/DrilldownIntegrationSpec.js
test/spec/features/modeling/behavior/SubProcessPlaneBehaviorSpec.js

When changing properties of the process, we created an infinite loop because the process plane does not have another representation in the diagram.
This PR ensures we only trigger `element.changed` if it is a subprocess.
try it out with `npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel#master -l bpmn-io/bpmn-js#allow-changes-to-root -c "npm run start:platform"`
related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/569

fix(drilldown): prevent infinite loop on root property change

---

lib/draw/BpmnRenderer.js
test/spec/draw/BpmnRendererSpec.js

+ clearly documented as *UNSAFE*
+ add test cases
+ tested existing *UNSAFE* handler endpoint

chore(draw): expose extension points

---

lib/features/modeling/BpmnUpdater.js
lib/features/modeling/behavior/RemoveEmbeddedLabelBoundsBehavior.js
lib/features/modeling/behavior/index.js
test/spec/features/modeling/BpmnUpdater.bpmn
test/spec/features/modeling/BpmnUpdaterSpec.js
test/spec/features/modeling/behavior/RemoveEmbeddedLabelBoundsBehavior.bpmn
test/spec/features/modeling/behavior/RemoveEmbeddedLabelBoundsBehaviorSpec.js

Direct issue is #1537
https://github.com/camunda/camunda-modeler/issues/2566
https://github.com/camunda/camunda-modeler/issues/2591
Doing a little write-up to get some ideas and feedback from people here. Note, this is a draft and is not trying to satisfy our definition of done yet. I'm mostly looking for input on implementation here.
Because we position embedded labels either centrally or center-top (as in expanded SubProcesses), we do not store their bounds information in `di`. This is not a problem for us, but causes issues with other vendors who do rely on these bounds for positioning.
Looking at the positioning of a task with such bounds for example, let move it a few grid points down:
Before:
```xml
<bpmndi:BPMNShape id="Activity_0cq51bw_di" bpmnElement="Activity_0cq51bw"> …
```

Update/Remove Embedded Label Bounds on Shape Moved/Resized

---

lib/features/modeling/behavior/SubProcessPlaneBehavior.js
test/spec/features/modeling/behavior/SubProcessPlaneBehaviorSpec.js

related to https://github.com/camunda/camunda-modeler/issues/2750
We did not make sure the changes we made in https://github.com/bpmn-io/bpmn-js/pull/1582 were reversible.
Test it out with `npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel#master -l bpmn-io/bpmn-js#undo-plane-id-change -c "npm run start:platform"`

fix(modeling): ensure plane ID change is undoable

---

lib/features/modeling/util/ModelingUtil.js
lib/util/ModelUtil.js
test/spec/util/ModelUtilSpec.js

This backports these important APIs to bpmn-js@8 for extensions to rely upon.
Makes is easier to work with both bpmn-js@8 and bpmn-js@9.
I've seen one to many test cases failing because either of them is missing.

Backport `ModelUtil#getDi` and `ModelUtil#isAny` to bpmn-js@8.x

---

lib/features/drilldown/SubprocessCompatibility.js
lib/features/modeling/behavior/ToggleCollapseConnectionBehaviour.js
test/spec/features/drilldown/legacy-subprocesses.bpmn

- Webpack polyfills `array.includes`, so our phantomJS tests are green even when they should not be. cf. https://github.com/bpmn-io/diagram-js/blob/develop/package-lock.json#L3385
- we assumed every DI has an associated a business Object. This assumption was removed.

Fix integration tests

---

lib/features/modeling/behavior/GroupBehavior.js
test/spec/features/modeling/behavior/GroupBehaviorSpec.bpmn
test/spec/features/modeling/behavior/GroupBehaviorSpec.js

closes #1606
We assumed that `definitions` is always the parent of the root element. This is not the case in subprocess planes.
Replaced the assumptions with a call to get the `getDefinitions()` method on the viewer.

fix(modeling): allways create Categories in `definitions`

---

assets/bpmn-js.css

Previously, the position of the breadcrumbs was determined in parts by the user agent stylesheet of the browser. With this PR, we remove padding and margin of the breadcrumbs and position it absolutely.
In the viewer, the breadcrumbs have the same distance from top and left, in the modeler it is positioned related to the Palette. The top distance stays the same in Modeler and Viewer.
Before: 
After:
cf. https://github.com/bpmn-io/bpmn-js-examples/pull/159#discussion_r811299406

fix(drilldown): override default padding of breadcrumb element

---

lib/features/drilldown/SubprocessCompatibility.js
lib/import/Importer.js
test/spec/features/drilldown/DrilldownSpec.js
test/spec/features/drilldown/legacy-subprocesses.bpmn

From what I got from the bpmn documentation, the Input/Output Associations are the only edge cases where the element is a child of the subprocess but rendered outside of it. Please correct me if I am missing something!
closes https://github.com/bpmn-io/bpmn-js/issues/1619

render dataAssociations on correct parent

---

lib/features/modeling/behavior/SubProcessStartEventBehavior.js
test/spec/features/modeling/behavior/SubProcessBehavior.start-event.bpmn
test/spec/features/modeling/behavior/SubProcessStartEventBehaviorSpec.js

Closes #1631
This p the same behaviour as the one applied to tasks:
https://user-images.githubusercontent.com/25825387/164481553-b55c4df2-24a1-4a08-b82c-cf9602474df1.mov

Add StartEvent when morphing from CallActivity to expanded SubProcess

---

lib/features/label-editing/cmd/UpdateLabelHandler.js
test/spec/features/modeling/UpdateLabelSpec.js

closes #1637
Integration-test this fix in linting:
`npx @bpmn-io/sr bpmn-io/bpmn-js-bpmnlint -l bpmn-io/bpmn-js#1637-delete-label-property `
- add label to shape
- remove label
- linting does not break

fix(label-editing): remove label property on empty label

---

lib/features/copy-paste/ModdleCopy.js
test/fixtures/json/model/custom.json
test/spec/features/copy-paste/ModdleCopySpec.js

Closes #1518
Issue stemmed from setting the parent here. When the array contained primitives, this led to trying to set a property on a primitive which is an exception. In general, the recursion itself handled the setting (or not) of parents depending on the array element type, so doing it here again is (unless I've missed something) redundant and in this case breaking.
Also thanks @pinussilvestrus for the test case.

fix(moddle-copy): primitive array copying

---

lib/draw/BpmnRenderUtil.js
lib/draw/BpmnRenderer.js
test/spec/draw/BpmnRendererSpec.js

`#000000` changed to `hsl(225, 10%, 15%)` according to [571](https://github.com/bpmn-io/diagram-js/issues/571).
---
Related to https://github.com/bpmn-io/diagram-js/issues/571

feat: change default black to off black

---

lib/features/auto-place/BpmnAutoPlaceUtil.js
lib/features/context-pad/ContextPadProvider.js
lib/features/modeling/behavior/LayoutConnectionBehavior.js
lib/features/modeling/behavior/index.js
lib/features/modeling/behavior/util/ConnectionLayoutUtil.js
lib/features/modeling/behavior/util/LabelLayoutUtil.js
lib/features/modeling/behavior/util/LayoutUtil.js
lib/features/rules/BpmnRules.js
package-lock.json
package.json
test/spec/features/auto-place/BpmnAutoPlace.bpmn
test/spec/features/auto-place/BpmnAutoPlaceSpec.js
test/spec/features/context-pad/ContextPad.activation.bpmn
test/spec/features/context-pad/ContextPadProviderSpec.js
test/spec/features/modeling/behavior/LayoutConnectionBehavior.bpmn
test/spec/features/modeling/behavior/LayoutConnectionBehaviorSpec.js
test/spec/features/rules/BpmnRulesSpec.js

related to https://github.com/camunda/camunda-modeler/issues/402

feat: allow TextAnnotation for SequenceFlows

---

lib/features/label-editing/LabelEditingProvider.js
test/spec/features/label-editing/LabelEditingProviderSpec.js

This is take two on fixing #1664, specifically https://github.com/bpmn-io/bpmn-js/issues/1664#issuecomment-1149805611:
Without this fix selection change would trigger direct editing completion before the delete listerer could cancel it.
---
Closes #1664

fix: cancel direct editing before element deletion

---

test/helper/index.js
test/spec/ModelerSpec.js

This allows us to enable different sorts of logging conveniently
via the test helper and control it via query parameters.
-----
The basic idea is that you can control via a query parameter if you'd like to log what is happening XML wise during a test run.

test: add generic logging facility

---

assets/bpmn-js.css
test/spec/features/align-elements/AlignElementsMenuProviderSpec.js

fix: properly size icons in distribute/align

---

lib/features/modeling/behavior/ReplaceElementBehaviour.js
test/spec/features/modeling/behavior/ReplaceElementBehaviourSpec.js

Closes #1696
Related to https://github.com/camunda/camunda-modeler/issues/2438

fix: check for replacement using actual target

---

lib/features/grid-snapping/behavior/GridSnappingAutoPlaceBehavior.js
lib/features/grid-snapping/behavior/GridSnappingLayoutConnectionBehavior.js
lib/features/grid-snapping/behavior/GridSnappingParticipantBehavior.js
lib/features/grid-snapping/behavior/index.js

Prevents clashes in behavior names (i.e. `CreateParticipantBehavior`).
---
I repeatedly stumbled upon insufficient namespacing in grid snapping behaviors, hence this PR.

chore(grid-snapping): rename / prefix behaviors

---

CHANGELOG.md
lib/features/copy-paste/BpmnCopyPaste.js
lib/features/copy-paste/ModdleCopy.js
lib/features/label-editing/LabelEditingProvider.js
lib/features/modeling/behavior/BoundaryEventBehavior.js
lib/features/modeling/behavior/GroupBehavior.js
lib/features/modeling/behavior/RootElementReferenceBehavior.js
lib/features/modeling/behavior/util/CategoryUtil.js
lib/features/modeling/cmd/UpdateModdlePropertiesHandler.js
test/spec/Modeler.copy-paste.complex.bpmn
test/spec/Modeler.copy-paste.empty.bpmn
test/spec/ModelerSpec.js
test/spec/features/copy-paste/BpmnCopyPasteSpec.js
test/spec/features/copy-paste/ModdleCopySpec.js
test/spec/features/copy-paste/collapsed-subprocess.bpmn
test/spec/features/copy-paste/data-associations.bpmn
test/spec/features/label-editing/LabelEditingProviderSpec.js
test/spec/features/modeling/behavior/BoundaryEventBehaviorSpec.js
test/spec/features/modeling/behavior/GroupBehaviorSpec.bpmn
test/spec/features/modeling/behavior/GroupBehaviorSpec.js
test/spec/features/modeling/behavior/RootElementReferenceBehaviorSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

This fixes a fundamental flaw in our copy mechanism.
Until today we would carry around a mutable copy of `oldBusinessObject` and `oldDi` that would change what has been copied if the copied element changes after the copy operation:
```
Copy <Task> with name <OLD>
Change <Task.name> property to <FOO>
Paste <Task'>
<Task'.name> is <FOO> despite it having name <OLD> at the time of copy
```
Unfortunately the PR got a little bigger than intended, fixing numerous small issues _and_ addition additional test coverage to test copy + paste end-to-end.
* fixes the issue by cloning each element _as we copy_. As a result what is copied is frozen at copy time and not affected by future changes anymore.
* fixes that paste behaviors would execute when pasting both labels and actual shapes …

Clone on copy

---

.eslintrc
CHANGELOG.md
lib/BaseViewer.js
package-lock.json
package.json
rollup.config.js
tasks/.eslintrc

* Migrated to ES2018 syntax. [Read the blog post with details and a migration guide](https://bpmn.io/blog/posts/2022-core-libraries-migrated-to-es2018.html).
---
Requires https://github.com/bpmn-io/bpmn.io/pull/147

Use ES2018 syntax

---

.github/workflows/POST_RELEASE.yml

For some reason, the integration test update downgraded the package-lock to version 1: https://github.com/bpmn-io/bpmn-js-integration/commit/be37eafd7def3ac48a37fe47eecf13b71c5d6189#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L4
I suspect that this was done due to outdated Node version, as the original image contains npm@8.

ci: use node@16 for post-release

---

package-lock.json
package.json
test/TestHelper.js

I found this to be useful (bring our test editors close to actual bpmn.io demo / modeler use-cases):

test: allow diagrams to be dropped onto active test editor

---

assets/bpmn-js.css
lib/features/align-elements/AlignElementsContextPadProvider.js
lib/features/context-pad/ContextPadProvider.js
package-lock.json
package.json
test/spec/features/context-pad/ContextPadProviderSpec.js
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

Closes #1775 
~~This is targeting `diagram-js@develop` since [this bug fix](https://github.com/bpmn-io/diagram-js/issues/695) was added after the alpha release. My idea is to pre-approve this to make sure the new popup menu is working as expected so we can have the stable release of `diagram-js`, and later integrate it here.~~
Integrate ~~`diagram-js@11.0.0`~~ `diagram-js@11.1.0`
Following the title discussion in the issue, I decided not to add the align title for now.

Integrate new popup menu

---

lib/features/context-pad/ContextPadProvider.js
lib/features/palette/PaletteProvider.js
package-lock.json
package.json

This builds on top of https://github.com/bpmn-io/bpmn-js/pull/1822 and further improves the visual presence of the single connection tool.
| _Before_ | _After_ |
| :--- | :--- |
| ![image](https://user-images.githubusercontent.com/58601/215989757-db3c4571-4ebb-4ff6-a29e-c5fba029e8bd.png) | ![image](https://user-images.githubusercontent.com/58601/215989487-1ea359b5-533f-43d4-8c97-b5300ebc10c9.png) |

Improve single connection presence

---

package-lock.json
package.json

Related to https://github.com/camunda/camunda-modeler/issues/2282

feat: use single arrow for connection icon

---

lib/draw/BpmnRenderer.js
package-lock.json
package.json

This PR ensures that we render paths on the diagram with `round` linecap / linejoin. This leads to a (slightly) improved, less harsh for the eye visual representation for shapes, connections, and markers.
---
Noteworthy glitches fixed:
* Sequence Flow end marker has _one_ out of three sharp corners
* Data Object looks aweful

Improve shape rendering / join path `round`

---

lib/draw/BpmnRenderer.js

This builds on top of #1827 and reworks rendering of different BPMN symbols:
* Group (alignment with BPMN 2.0 spec, improved visual presence)
* Participant / Lane (decreased visual presence)
* Event Sub-Process (alignment with BPMN 2.0 spec)
* Transaction (adjusted visual presence)
* Intermediate Event / Boundary Event (adjusted visual presence)
* ...

Rework BPMN symbol rendering

---

lib/draw/BpmnRenderer.js

This adds round corner rendering for sequence and message flows. Builds on top of https://github.com/bpmn-io/diagram-js/pull/747.
Compare complex to [current version](https://demo.bpmn.io/s/application-processing).
----
Depends on https://github.com/bpmn-io/diagram-js/pull/747

Round connection corners

---

lib/BaseModeler.js
lib/BaseViewer.js
lib/Modeler.js
lib/Viewer.js
test/spec/BaseModelerSpec.js
test/spec/BaseViewerSpec.js

Implements what we discussed in https://github.com/camunda/camunda-bpmn-js/issues/236#issuecomment-1418735028 and following.

Get module context

---

CHANGELOG.md
lib/features/create-append-anything/AppendMenuProvider.js
lib/features/create-append-anything/CreateMenuProvider.js
lib/features/create-append-anything/util/OptionsUtil.js
lib/features/replace/ReplaceOptions.js
package-lock.json
package.json

This closes https://github.com/bpmn-io/bpmn-js/issues/1621 in two ways:
* Initially rare elements are not shown in create/append anything menus
* User and service tasks are moved up in the menu to make them more prominent
---

Improve semantic ordering / filter rare elements

---

lib/draw/BpmnRenderer.js

Reverts https://github.com/bpmn-io/bpmn-js/commit/eb4b54f7ffdb55e340aac291c33a5f4d66e246b3 as it breaks image export.
Related to https://github.com/camunda/camunda-modeler/issues/3442.

fix: restore marker `stroke-dasharray` 2015 workaround

---

lib/features/replace-preview/BpmnReplacePreview.js
package-lock.json
package.json

refactor: replace `css.escape` npm module with builtin API

---

CHANGELOG.md
lib/features/modeling/behavior/RootElementReferenceBehavior.js
test/spec/features/modeling/behavior/RootElementReferenceBehavior.bpmn
test/spec/features/modeling/behavior/RootElementReferenceBehaviorSpec.js

This is so that I don't need to manually add root element when updating messageRef or event definitions.

feat: add root elements to definitions for updates

---

rollup.config.js
tasks/build-distro.js

Allows us to get rid of some rollup@3 magic.

chore: bundle rollup config as CJS

---

lib/BaseViewer.d.ts
lib/BaseViewer.spec.ts

Related to https://github.com/bpmn-io/bpmn-js/pull/1881

fix: correct `BaseViewer#saveXML` definition

---

lib/draw/BpmnRenderer.js
test/spec/draw/BpmnRenderer.no-event-icons.bpmn
test/spec/draw/BpmnRendererSpec.js
test/spec/draw/custom-renderer/CustomRenderer.js
test/spec/draw/custom-renderer/index.js

This adds a new option to the `BpmnRenderer` to render events without icons. The use-case is customizing (cf. https://github.com/bpmn-io/element-template-icon-renderer/issues/6).
For detailed usage, checkout https://github.com/bpmn-io/bpmn-js/pull/1917/files#diff-c8205dfe6f35f2b861d97b83d680753e34aea03b27bbeee25bc42d8579604807R52.

Allow event rendering without icons

---

lib/features/align-elements/AlignElementsContextPadProvider.js
lib/features/align-elements/AlignElementsIcons.js
lib/features/align-elements/AlignElementsMenuProvider.js
lib/features/align-elements/resources/align-bottom-tool.svg
lib/features/align-elements/resources/align-horizontal-center-tool.svg
lib/features/align-elements/resources/align-left-tool.svg
lib/features/align-elements/resources/align-right-tool.svg
lib/features/align-elements/resources/align-tool.svg
lib/features/align-elements/resources/align-top-tool.svg
lib/features/align-elements/resources/align-vertical-center-tool.svg
lib/features/distribute-elements/DistributeElementsIcons.js
lib/features/distribute-elements/DistributeElementsMenuProvider.js
lib/features/distribute-elements/resources/distribute-horizontally-tool.svg
lib/features/distribute-elements/resources/distribute-vertically-tool.svg
package-lock.json
package.json
test/spec/features/align-elements/AlignElementsMenuProviderSpec.js

Load icons as html

---

.github/workflows/POST_RELEASE.yml
.github/workflows/UPDATE_TRANSLATIONS.yml
tasks/stages/update-translations

This allows to trigger translations update at convenience.
Related to https://github.com/bpmn-io/bpmn-js/actions/runs/5177347753/jobs/9327333594

ci: extract translations update to separate workflow

---

CHANGELOG.md
lib/BaseViewer.js
test/spec/ViewerSpec.js

As a follow-up to https://github.com/bpmn-io/bpmn-js/pull/1939 this removes the long deprecated `import.parse.complete` member `context`.
* `import.parse.complete` member `context` removed. Use the actual event to retrieve error, warning, and references information.
----
Deprecated since `v7.0.0` (released 3 years ago).

chore: drop deprecated `context` member

---

lib/features/modeling/behavior/EventBasedGatewayBehavior.js
test/spec/features/modeling/behavior/EventBasedGatewayBehaviorSpec.js

The change ensures that if a connection is scaffolded as part of `create` then it is not removed right during placement.
Closes https://github.com/bpmn-io/bpmn-js/issues/1490

fix: allow to create connection + event-based gateway

---

lib/features/modeling/behavior/FixHoverBehavior.js
package-lock.json
package.json
test/spec/features/modeling/behavior/FixHoverBehaviorSpec.js

* integrate diagram-js v12.4.0
* ensure ensure lanes aren't resized without their parent participant when using space tool

Integrate Local Space Tool

---

lib/features/popup-menu/ReplaceMenuProvider.js
test/fixtures/bpmn/draw/activity-markers-simple.bpmn
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

fix: set loop characteristics in a command

---

.github/workflows/POST_RELEASE.yml
.github/workflows/RELEASE.yml
.github/workflows/UPDATE_TRANSLATIONS.yml

Closes #1979
We are using release-please action outputs in this solution: https://github.com/google-github-actions/release-please-action#outputs

ci: fix POST_RELEASE job

---

CHANGELOG.md
lib/draw/BpmnRenderUtil.js
lib/draw/BpmnRenderer.js
lib/features/append-preview/AppendPreview.js
lib/features/append-preview/index.js
lib/features/context-pad/ContextPadProvider.js
lib/features/context-pad/index.js
test/fixtures/bpmn/kitchen-sink.bpmn
test/spec/draw/BpmnRendererSpec.js
test/spec/features/append-preview/AppendPreview.bpmn
test/spec/features/append-preview/AppendPreviewSpec.js
test/spec/features/context-pad/ContextPadProviderSpec.js
test/spec/features/modeling/behavior/ReplaceElementBehaviourSpec.js
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

* context pad
* preview append on hover
* renderer
* `fill`, `stroke`, `width` and `height` can be overridden
* no other attributes can be overridden
* public API only exposes renderers for actual BPMN elements
* https://github.com/bpmn-io/diagram-js/issues/816
---
Closes https://github.com/bpmn-io/bpmn-js/issues/1990

Preview Append

---

lib/features/modeling/behavior/NonInterruptingBehavior.js
lib/features/modeling/behavior/index.js
lib/features/modeling/behavior/util/NonInterruptingUtil.js
lib/features/popup-menu/ReplaceMenuProvider.js
lib/features/popup-menu/util/Icons.js
lib/features/replace/BpmnReplace.js
lib/features/replace/ReplaceOptions.js
package-lock.json
package.json
test/spec/features/modeling/behavior/AttachEventBehaviorSpec.js
test/spec/features/modeling/behavior/NonInterruptingBehavior.bpmn
test/spec/features/modeling/behavior/NonInterruptingBehaviorSpec.js
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
test/spec/features/replace/BpmnReplaceSpec.js

This PR adds 2 new features:
- Keep the interrupting state when replacing elements, when the interrupting state is not explicitly set. This is used when element-templates are applied to events  
- Add a toggle header button to non-interrupting events
related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/20
You can try out the integration with element templates here: https://marstamm.github.io/non-interrupting-modeling-demo/

feat(modeling): keep interrupting config when replacing elements

---

lib/features/outline/OutlineProvider.js
test/spec/features/outline/OutlineProvider.bpmn
test/spec/features/outline/OutlineProviderSpec.js

fix(outline): external label resize

---

lib/features/outline/OutlineProvider.js

Closes #2015
This happens because the events all have the same diameter but end even has a thicker stroke.

fix(outline): end event

---

lib/draw/BpmnRenderer.js
lib/features/label-editing/LabelEditingProvider.js
lib/features/modeling/behavior/IsHorizontalFix.js
lib/util/DiUtil.js
test/fixtures/bpmn/draw/vertical-pools.bpmn
test/spec/draw/BpmnRendererSpec.js
test/spec/features/label-editing/LabelEditing.bpmn
test/spec/features/label-editing/LabelEditingProviderSpec.js
test/spec/features/modeling/behavior/IsHorizontalFix.bpmn
test/spec/features/modeling/behavior/IsHorizontalFixSpec.js

Hi there,
I propose an implementation for rendering vertical pools and lanes.
Fixes #57 
The labels of vertical pools and lanes as well as the pool label separator are now correctly rendered on top.
Labels of vertical black-box pools are rotated.
The spec implies that horizontal is the default and I adhere to that, i.e. a missing isHorizontal attribute defaults to true.
Could you please provide some information how I can test this?
I thought about adding a vertical version of https://github.com/bpmn-io/bpmn-js/blob/7aee439f47cf0daebcb6131e84f0f9a9d2a51544/test/fixtures/bpmn/draw/pools.bpmn
...but I'm not quite sure if that'll do it.
Kind regards
<details>
<summary>Showcase</summary>
</details>

Render Vertical Participants and Lanes

---

tasks/stages/update-examples

This ensures that the examples is in an installable state after we updated it.
Closes https://github.com/bpmn-io/bpmn-js/issues/2059

ci: update examples lock file POST_RELEASE

---

lib/features/modeling/behavior/CompensateBoundaryEventBehavior.js
test/spec/features/modeling/behavior/CompensateBoundaryEventBehavior.bpmn
test/spec/features/modeling/behavior/CompensateBoundaryEventBehaviorSpec.js

Event though we are removing existing associations during `preExecute` when creating a connection in the case of copy and paste the new connection can already be connected to source and target so we have to make sure we're not trying to remove that connection.
Closes #2068

fix: do not remove association that was just created

---

lib/features/modeling/behavior/FixHoverBehavior.js
lib/features/modeling/behavior/TextAnnotationBehavior.js
lib/features/modeling/behavior/index.js
lib/features/ordering/BpmnOrderingProvider.js
test/spec/features/copy-paste/BpmnCopyPasteSpec.js
test/spec/features/modeling/append/TextAnnotationSpec.js
test/spec/features/modeling/behavior/FixHoverBehavior.annotation.bpmn
test/spec/features/modeling/behavior/FixHoverBehaviorSpec.js
test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js
test/spec/features/modeling/behavior/TextAnnotationBehaviorSpec.bpmn
test/spec/features/modeling/behavior/TextAnnotationBehaviorSpec.js

- render Annotations always on top
- Disable auto-resize for text annotations
closes https://github.com/bpmn-io/bpmn-js/issues/2049

feat: adjust TextAnnotations behavior

---

lib/features/modeling/behavior/DeleteLaneBehavior.js
test/spec/features/modeling/lanes/DeleteLaneSpec.js
test/spec/features/modeling/lanes/lanes.vertical.bpmn

Closes #2081
This is a small independent fix.

Delete Vertical Lanes

---

lib/features/modeling/ElementFactory.js
lib/features/palette/PaletteProvider.js
test/spec/features/modeling/ElementFactorySpec.js

Closes #2063 
I think it was a mistake to rely on `attrs`. Without it, this is the most simple solution I found. Please have a look.

Rendering of Gateway Without Marker

---

.github/CONTRIBUTING.md

The language version constructs are guarded by the linter, so there is no need to ask users to adhere to additional conventions. Also, we allow up to ES2019 now.

chore: remove code style conventions section

---

lib/features/auto-place/BpmnAutoPlaceUtil.js
lib/features/modeling/BpmnLayouter.js
lib/features/modeling/util/ModelingUtil.js
test/spec/features/auto-place/BpmnAutoPlace.vertical.boundary-events.bpmn
test/spec/features/auto-place/BpmnAutoPlace.vertical.bpmn
test/spec/features/auto-place/BpmnAutoPlace.vertical.multi-connection.bpmn
test/spec/features/auto-place/BpmnAutoPlaceSpec.js
test/spec/features/modeling/behavior/RemoveElementBehavior.vertical.diagonal.bpmn
test/spec/features/modeling/behavior/RemoveElementBehaviorSpec.js
test/spec/features/modeling/layout/LayoutMessageFlowSpec.js
test/spec/features/modeling/layout/LayoutMessageFlowSpec.vertical.bpmn
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.vertical.boundaryEvents.bpmn
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.vertical.boundaryEventsLoops.bpmn
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.vertical.flowElements.bpmn
test/spec/features/modeling/layout/LayoutSequenceFlowSpec.vertical.subProcess.bpmn

Closes #2110
This implements auto place and flow layouting for vertical pools and lanes and works only within those containers.
It's an almost exact mapping of the horizontal layout.
The exception: Per #2110, data objects are placed to the left of tasks and text annotations are placed to their right (only for vertical layouts).
Since data objects are not avilable by default, you can use this Context Pad code for testing (insert near `append.append-task`):
```
'append.data-store': appendAction(
'bpmn:DataStoreReference',
'bpmn-icon-data-store',
'Data Store TEST'
),
'append.data-object': appendAction(
'bpmn:DataObjectReference',
'bpmn-icon-data-object',
'Data Object TEST'
),
```
The initial dimensions and content of sub processes are still laid out horizontally.
I think that's a feature for …

 Vertically Auto-Place Elements

---

lib/Modeler.js
lib/Viewer.js

Custom outlines were only included in modeler.
Closes https://github.com/bpmn-io/bpmn-js/issues/2133

Fix outlines

---

lib/features/modeling/BpmnUpdater.js
lib/features/modeling/ElementFactory.js
lib/features/modeling/behavior/UpdateFlowNodeRefsBehavior.js
lib/features/modeling/cmd/SplitLaneHandler.js
lib/features/modeling/cmd/UpdatePropertiesHandler.js
lib/features/ordering/BpmnOrderingProvider.js
lib/features/ordering/index.js
lib/import/BpmnImporter.js
lib/import/BpmnTreeWalker.js
lib/import/Importer.js

This PR proposes a change in how we handle technical errors: These are no longer translated, both during modeling _and_ during import.
Due to the nature of _technical_ errors it makes little sense to localize them. If I need help on how to fix a particular technical issue, then I want to search for these errors _as is_.
Closes https://github.com/bpmn-io/internal-docs/issues/937
Related to https://github.com/bpmn-io/bpmn-js/pull/2137

Do not translate technical errors

---

CHANGELOG.md
lib/features/label-editing/LabelEditingProvider.js
package-lock.json
package.json

With this PR, we explicitly set when direct editing should have a background and disable it for all other cases.
related to https://github.com/camunda/web-modeler/issues/8477

feat(label-editing): remove background for embedded labels

---

lib/features/context-pad/ContextPadProvider.js
test/spec/features/context-pad/ContextPadProviderSpec.js

fix(context-pad): remove append preview on context pad close

---

lib/BaseModeler.js
lib/BaseModeler.spec.ts
lib/BaseViewer.js
lib/BaseViewer.spec.ts
lib/Modeler.js
lib/Modeler.spec.ts
lib/NavigatedViewer.js
lib/NavigatedViewer.spec.ts
lib/Viewer.js
lib/Viewer.spec.ts

This adds the ability to type the contents of your bpmn-js powered editor:
----
Closes https://github.com/bpmn-io/bpmn-js/issues/2121

Type hints

---

lib/import/Importer.js
test/spec/import/ImporterSpec.js
test/spec/import/missing-di-plane-root-element.bpmn
test/spec/import/missing-di-plane.bpmn

Without this change any auxiliary `<bpmndi:BPMNDiagram />` without a plane would crash the importer.
Now the (broken) BPMN diagram is simply ignored during import.
----
Related to https://github.com/bpmn-io/bpmnlint/pull/135

fix(import): handle missing BPMNDiagram#plane

---

lib/features/drilldown/SubprocessCompatibility.js
test/spec/features/drilldown/DrilldownSpec.js
test/spec/features/drilldown/missing-di-bpmndiagram-plane.bpmn

Previously we'd scroll through all diagrams, assuming `plane` would always be set.

Gracefully handle missing `BPMNDiagram#plane` in legacy sub-process behavior

---

lib/features/modeling/Modeling.js
lib/features/modeling/behavior/RemoveParticipantBehavior.js
test/fixtures/bpmn/collaboration/collaboration-data-store.bpmn
test/spec/features/modeling/behavior/RemoveParticipantBehaviorSpec.js

feat(modeling): keep global elements when deleting last participant

---

CHANGELOG.md
lib/BaseViewer.js
lib/draw/BpmnRenderer.js
package-lock.json
package.json
test/spec/draw/BpmnRendererSpec.js

This allows styling with `canvas.addMarker` and css, as described in our [examples](https://github.com/bpmn-io/bpmn-js-examples/blob/main/colors/README.md#option-3-color-via-marker--css-styling).
Requires https://github.com/bpmn-io/diagram-js/pull/906
related to https://github.com/camunda/camunda-modeler/issues/4307

feat: render markers as part of djs-visual

---

package-lock.json
package.json

Improves [`clear`](https://github.com/bpmn-io/tiny-svg/blob/main/lib/clear.js), a heavily used utility. Trying a modern API [did not](https://github.com/bpmn-io/diagram-js/pull/910) yield the desired effect.

deps: update to min-dom@4.2.1 / tiny-svg@3.1.2

---

lib/features/drilldown/DrilldownOverlayBehavior.js
package-lock.json
package.json
test/spec/ModelerSpec.js
test/spec/NavigatedViewerSpec.js
test/spec/ViewerSpec.js
test/spec/features/drilldown/DrilldownSpec.js

This PR:
* replaces `axe-core` with `@bpmn-io/a11y` to ensure common a11y goal
* adds accessible label to drill down button via `title`
Related to https://github.com/camunda/camunda-modeler/issues/4394

Add accessible label to drill down button

---

lib/features/context-pad/ContextPadProvider.js
test/spec/features/context-pad/ContextPadProviderSpec.js

Closes #2163
Show delete action for element's label.

fix: show delete action for labels

---

lib/features/modeling/Modeling.js

This only fixes the jsdoc param for `attrs` in modeling connect being typed as required while it's optional.
If this was intended to be required, I can also delete this PR.

docs(modeling): improve connect optional param jsdoc definition

---

lib/features/context-pad/ContextPadProvider.js

Fix the [issue](https://github.com/bpmn-io/bpmn-js/issues/2203). Added type to the function's constructor.
Related to {https://github.com/bpmn-io/bpmn-js/issues/2203}
* [] **Visual demo** attached
* [] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

fixed ContextPadProvider types

---

lib/features/modeling/ElementFactory.js
lib/features/replace/BpmnReplace.js
test/spec/features/replace/BpmnReplace.collaboration.vertical.bpmn
test/spec/features/replace/BpmnReplace.poolMessageFlows.vertical.bpmn
test/spec/features/replace/BpmnReplaceSpec.js

Closes #2208
When collapsing or expanding a pool, the direction (horizontal/vertical) remains intact. This works with the existing UI.
The safeguard for message flows (keeping the pool's length) works with any pool.
<details>
<summary>Visual demo</summary>
</details>

Keep Direction When Collapsing/Expanding Pools

---

CHANGELOG.md
lib/features/modeling/behavior/ResizeBehavior.js
test/spec/features/modeling/behavior/ResizeBehaviorSpec.js

**Issue:** The lane resize constraints do not work when using any lane except for the lowest one of the participant and using the bottom right corner of the lane.
**Resolution:** Fixed lane resizing when multiple lanes exist with participants from NW and SE direction. 
**Identified Issue:** isFirst and isLast flag was not setting with corresponding lanes during resizing. 
Closes #2209

fix: lane resize constraint 

---

lib/features/search/BpmnSearchProvider.js
package-lock.json
package.json
test/spec/features/search/BpmnSearchProviderSpec.js
test/spec/features/search/bpmn-search-sorting.bpmn

Improves search by
* sorting matches by location (when searching for "foo", "foo bar" will appear before "bar foo")
Depends on https://github.com/bpmn-io/diagram-js/pull/913
Closes https://github.com/bpmn-io/bpmn-js/issues/2189

Search improvements

---

lib/features/search/BpmnSearchProvider.js
test/spec/features/search/BpmnSearchProviderSpec.js
test/spec/features/search/bpmn-search-sorting.bpmn

Elements like associations don't have any label which we could use for comparison when sorting the search results.
Closes https://github.com/bpmn-io/bpmn-js/issues/2232

Handle elements without label when using search

---

lib/util/LabelUtil.js
test/spec/features/modeling/UpdateLabel.bpmn
test/spec/features/modeling/UpdateLabelSpec.js

Closes #2231
- Enter whitespaces in group labels doesn't crash modeler 
- Whitespaces will be treated as no label

fix: empty whitespaces label in group

---

lib/.eslintrc
package-lock.json
package.json

This uses `bpmn-moddle@9`, a release that cleans up some [existing legacy](https://github.com/bpmn-io/bpmn-moddle/blob/main/CHANGELOG.md#900).
The library, as well as upstream now expose true ES modules, and still expose CJS modules for use. The library also requires Node@18 (Node@16 is [out of maintainance](https://nodejs.org/en/about/previous-releases) since 2023).
For safety reasons I'd regard this as a breaking change that we want to batch with other breaking changes (if any).

Update to `bpmn-moddle@9`

---

lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js
test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehavior.basics.bpmn
test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehaviorSpec.js

Closes #2239 
Text annotation can now co exist with flow element label 
Requires upstream: https://github.com/bpmn-io/diagram-js/pull/940

2239 text annotation alignment

---

lib/features/popup-menu/ReplaceMenuProvider.js
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

Partially addresses https://github.com/camunda/camunda-modeler/issues/4310.
Related to https://github.com/camunda/camunda-modeler/issues/4310

fix(replace-menu): keep existing loop characteristics

---

CHANGELOG.md
lib/Viewer.js
package-lock.json
package.json
test/spec/ViewerSpec.js

We don't want to include outline module by default in `Viewer` modules to not include any visueal, non core functionalities
Closes #2135

Remove outline module from default modules in Viewer

---

CHANGELOG.md
lib/features/search/BpmnSearchProvider.js
lib/features/search/index.js
package-lock.json
package.json
test/spec/draw/BpmnRendererSpec.js
test/spec/features/search/BpmnSearchProviderSpec.js

This plugs into the new `search` utility shipped with https://github.com/bpmn-io/diagram-js/pull/916 / [diagram-js@14.11.0](https://github.com/bpmn-io/diagram-js/blob/develop/CHANGELOG.md#14110), now updated and fixed via https://github.com/bpmn-io/diagram-js/pull/932:
Try out via
```
npx @bpmn-io/sr bpmn-io/bpmn-js#use-search
```
---
Depends on https://github.com/bpmn-io/diagram-js/pull/932

Use search

---

lib/Modeler.js
test/spec/ModelerSpec.js
test/spec/ViewerSpec.js

Turns out our custom outlines got missing with 583195a, time to restore them (for modeling).
Related to #2135

fix(Modeler): re-add outline feature

---

lib/BaseViewer.js
test/spec/ViewerSpec.js

Ensures that the canvas is first in the focus / accessibility hierarchy of the browser:
Without the fix the browser would tab through the diagram like this:
```
bpmn.io logo
canvas
```

fix(BaseViewer): swap canvas and project logo

---

lib/features/popup-menu/ReplaceMenuProvider.js
lib/features/replace/BpmnReplace.js
lib/features/replace/ReplaceOptions.js
test/spec/features/modeling/behavior/ToggleElementCollapseBehaviour.bpmn
test/spec/features/modeling/behavior/ToggleElementCollapseBehaviourSpec.js
test/spec/features/popup-menu/ReplaceMenuProvider.subProcesses.bpmn
test/spec/features/popup-menu/ReplaceMenuProviderSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/4801
Make ad-hoc subprocess available as a replace menu entry.
https://github.com/user-attachments/assets/459386fd-e4be-4999-8ebe-49fcca2b40cf

Create ad-hoc sub process via replace menu

---

lib/features/space-tool/BpmnSpaceTool.js
test/spec/features/space-tool/BpmnSpaceTool.artifacts.bpmn
test/spec/features/space-tool/BpmnSpaceTool.participants.bpmn
test/spec/features/space-tool/BpmnSpaceToolSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/4172
When using the space tool locally inside of a participant, it now moves text annotations that are enclosed by it.
Unlike labels, text annotations that are outside of the participant won't move even if their target is in the participant.
https://github.com/user-attachments/assets/03daff09-61d7-4f47-a848-82236ffd7e31

fix: move text annotations when a participant is resized by space tool

---

lib/draw/BpmnRenderer.js
test/fixtures/bpmn/draw/event-subprocess-icons.bpmn
test/spec/draw/BpmnRendererSpec.js

Closes #50
Draw event icons for collapsed event subprocesses.
No icon is drawn when a start event is missing or when there's more than one start event (forbidden by the spec).
Reuses existing code with few minor adjustments.
Demo (spec on the right):
[event-subprocess-icons.bpmn](https://github.com/sombrek/bpmn-js/blob/event-subprocess-icons/test/fixtures/bpmn/draw/event-subprocess-icons.bpmn) contains all possible icons.

feat: render event subprocess icons

---

lib/features/context-pad/ContextPadProvider.js
lib/import/BpmnTreeWalker.js
test/fixtures/bpmn/import/text-annotation-message-flow.bpmn
test/spec/features/auto-place/BpmnAutoPlace.bpmn
test/spec/features/auto-place/BpmnAutoPlaceSpec.js
test/spec/features/context-pad/ContextPad.activation.bpmn
test/spec/features/context-pad/ContextPadProviderSpec.js
test/spec/features/modeling/behavior/LayoutConnectionBehavior.bpmn
test/spec/features/modeling/behavior/LayoutConnectionBehaviorSpec.js
test/spec/features/rules/BpmnRulesSpec.js
test/spec/import/ImporterSpec.js

added ability to add a text annotation to a message flow
closes #2281

feat: allow text annotations for message flows

---

lib/features/copy-paste/ModdleCopy.js
lib/util/ModelUtil.js
test/spec/features/copy-paste/ModdleCopySpec.js
test/spec/features/modeling/behavior/BoundaryEventBehaviorSpec.js

Closes #2249, #1906
Related to: https://github.com/camunda/camunda-modeler/issues/4863, https://github.com/camunda/camunda-modeler/issues/4567
Event references now retain the same reference even when the associated element is changed.
Specifically handled event definitions:
- `bpmn:ErrorEventDefinition`
- `bpmn:EscalationEventDefinition`
- `bpmn:MessageEventDefinition`
- `bpmn:SignalEventDefinition`
You can try it out via 
```
npx @bpmn-io/sr camunda/camunda-bpmn-js -l bpmn-io/bpmn-js#event-refs
```

Event references not removed when element is replaced

---

CHANGELOG.md
lib/Modeler.js
lib/Viewer.js
test/spec/ModelerSpec.js
test/spec/ViewerSpec.js

Closes #2302 
- When I select the elements using `Cmd + Click`, some text is also selected along the way which is not the case with modeler.
- Flow elements are not selected when selected individually since they don't have outline.
- Modeler single element select. Can select flow elements but I guess it's not an outline.
run `npm run start:viewer` to see outline is available in viewer
run `npm start` to see outline is available in the modeler (via viewer)

Selection outline is available by default from Viewer and not Modeler

---

CHANGELOG.md
lib/Modeler.js
lib/Viewer.js
test/spec/ModelerSpec.js
test/spec/ViewerSpec.js

Reverted selection outline in viewer. (ref. https://github.com/bpmn-io/bpmn-js/pull/2316, https://camunda.slack.com/archives/GP70M0J6M/p1747036031927819)

Selection outline reverted. Available via modeler only.

---

lib/draw/BpmnRenderer.js
test/fixtures/bpmn/draw/activity-markers-simple.bpmn
test/spec/draw/BpmnRendererSpec.js

Center a task marker if it's the only marker on a task.
Correctly position multiple markers close to the center if there are multiple. We don't try to center all markers together, just put new markers to the sides of already existing ones, as close to the center as possible.
The tests are a little nilly-willy, cause there are too many combinations, so I mostly rely on manual testing.
Closes https://github.com/bpmn-io/bpmn-js/issues/1995 
Related to https://github.com/camunda/camunda-modeler/issues/4806

fix: center task markers; adjust position of multiple markers

---

test/spec/.eslintrc

It looks that we forgot to remove it in the eslint@9 migration.

chore: remove redundant eslintrc

---

.github/workflows/COMMENT_TARGETS_MAIN.yml

Related to bpmn-io/internal-docs#1206
Add a github action that adds a comment if the target branch of a PR is main, (we want to target develop by default).
See for example the comment in this PR. But in this case I actually want to target main directly

ci: add comment on PRs targeting main
