lib/features/modeling/cmd/SetColorHandler.js, lib/features/modeling/cmd/UpdatePropertiesHandler.js, test/spec/ModelerSpec.js, test/spec/features/modeling/UpdatePropertiesSpec.js
Relevant fix commit: https://github.com/bpmn-io/bpmn-js/commit/a26d6f421c596b189c4d66520edd98cea93b902b.
Ensures we don't set `di` property on `businessObject` on update.
Fixes #756
=> 756 colors di

lib/features/rules/BpmnRules.js, test/spec/features/rules/BpmnRules.compensation-collaboration.bpmn, test/spec/features/rules/BpmnRulesSpec.js
Related to camunda/camunda-modeler#661
=> fix(modeling/rules): make compensation activity a message flow source

lib/features/label-editing/LabelEditingProvider.js, test/spec/features/label-editing/LabelEditingProviderSpec.js
=> fix(label-editing): complete on autoPlace start

CHANGELOG.md, lib/features/modeling/BpmnUpdater.js, test/spec/features/modeling/BpmnUpdater.incompleteDi.bpmn, test/spec/features/modeling/BpmnUpdater.missingBounds.bpmn, test/spec/features/modeling/BpmnUpdaterSpec.js
=> fix(modeling): correctly handle missing bpmndi:Label bounds

lib/draw/TextRenderer.js, lib/features/label-editing/LabelEditingProvider.js, package.json, test/spec/draw/TextRendererSpec.js, test/spec/features/label-editing/LabelEditingProviderSpec.js, test/spec/features/modeling/LabelLayoutingSpec.js, test/spec/features/modeling/behavior/LabelBehaviorSpec.js, test/spec/import/elements/LabelSpec.js
=> 803 apply font family weight

CONTRIBUTING.md
Clarify our style guidelines with regards to ES language constructs.
=> chore(CONTRIBUTING): add ES code style hint

lib/features/label-editing/LabelEditingProvider.js, lib/features/label-editing/cmd/UpdateLabelHandler.js, lib/features/modeling/Modeling.js, lib/features/modeling/behavior/LabelBehavior.js, test/spec/features/label-editing/LabelEditingProviderSpec.js, test/spec/features/modeling/UpdateLabelSpec.js, test/spec/features/modeling/behavior/LabelBehaviorSpec.js
=> Fix label behavior

CHANGELOG.md, lib/features/replace/BpmnReplace.js, test/fixtures/bpmn/features/replace/01_replace.bpmn, test/matchers/JSONMatcher.js, test/spec/features/replace/BpmnReplaceSpec.js
=> Keep event definitions

CHANGELOG.md, lib/features/modeling/BpmnLayouter.js, lib/features/rules/BpmnRules.js, test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js, test/spec/features/rules/BpmnRulesSpec.js
Depends on https://github.com/bpmn-io/diagram-js/pull/269
* rules allow modeling loops
* loops will be laid out properly
=> Allow modeling of loops

package.json, test/config/karma.unit.js, test/spec/import/BpmnTreeWalkerSpec.js, test/suite.js
* use karma-webpack
* no more transpilation in dev setup
=> Drop browserify + babelify from build chain

CHANGELOG.md, lib/features/modeling/behavior/DropOnFlowBehavior.js, lib/features/rules/BpmnRules.js, test/spec/features/modeling/behavior/DropOnFlowBehavior.bpmn, test/spec/features/modeling/behavior/DropOnFlowBehaviorSpec.js, test/spec/features/rules/BpmnRules.insert.bpmn, test/spec/features/rules/BpmnRulesSpec.js, test/spec/features/rules/Helper.js
Fix multiple scenarios where drop on flow could lead to too many connections being created (#836, #774).
Closes #836 
Closes #774
=> Fix duplicate flows

lib/features/rules/BpmnRules.js, test/spec/features/rules/BpmnRules.collaboration.bpmn, test/spec/features/rules/BpmnRulesSpec.js, test/spec/features/rules/Helper.js
=> 849 message flow label error

lib/features/modeling/BpmnLayouter.js, lib/features/snapping/BpmnSnapping.js, test/spec/features/snapping/BpmnSnapping.connect.bpmn, test/spec/features/snapping/BpmnSnappingSpec.js
=> 850 snap events message flow

lib/features/rules/BpmnRules.js, test/spec/features/rules/BpmnRules.moveLane.bpmn, test/spec/features/rules/BpmnRulesSpec.js
=> fix(rules): correct bpmn:Lane insert rule

lib/features/context-pad/ContextPadProvider.js
* adjust tooltip titles
* i18n support
=> feat(contextPad): Adjustments for  IntermediateCatchEvents

package.json
* fixes broken isDefined / isUndefined utils
=> chore(project): bump min-dash dependency

lib/draw/BpmnRenderer.js, test/fixtures/bpmn/draw/group-name.bpmn, test/spec/draw/BpmnRendererSpec.js
Adjust renderer of `bpmn:Group` by appending name from related CategoryValue
Closes #844
=> feat(bpmn-renderer): render group names

CHANGELOG.md
=> chore(CHANGELOG): update to v3.0.1

.gitignore, .npmrc, package-lock.json
Ensure we don't accidentally include new malicious dependencies.
=> chore(project): re-introduce package-lock

lib/features/modeling/behavior/RemoveElementBehavior.js, test/spec/features/replace/BpmnReplace.poolMessageFlows.bpmn, test/spec/features/replace/BpmnReplaceSpec.js
=> fix(modeling): limit flow join behavior to bpmn:SequenceFlows

package-lock.json, package.json, test/config/karma.distro.js, test/config/karma.unit.js
* yields performance gains up to 30% compared to spec reporter
=> test(project): use built-in progress reporter

lib/features/modeling/behavior/IsHorizontalFix.js, lib/features/modeling/behavior/index.js, test/spec/features/modeling/behavior/IsHorizontalFix.bpmn, test/spec/features/modeling/behavior/IsHorizontalFixSpec.js
=> feat(modeling): add isHorizontal=true to participant/lane shapes

lib/import/BpmnImporter.js, test/spec/features/modeling/behavior/ToggleElementCollapseBehaviour.bpmn, test/spec/features/modeling/behavior/ToggleElementCollapseBehaviourSpec.js, test/spec/import/ImporterSpec.js, test/spec/import/sequenceFlow-missingWaypoints.bpmn
https://github.com/bpmn-io/bpmn-js/commit/7a8792a6698f2618f0f0db708b82a2ef5fa1324f makes sure that we gracefully handle missing waypoints during import.
Fixes https://github.com/camunda/camunda-modeler/issues/1294
=> Missing waypoints

lib/features/label-editing/LabelUtil.js, lib/util/LabelUtil.js, test/spec/ModelerSpec.js, test/spec/features/label-editing/LabelEditing.bpmn, test/spec/features/label-editing/LabelEditingProviderSpec.js, test/spec/features/modeling/input-output/DataInputOutput.bpmn, test/spec/import/elements/DataInputOutput.bpmn, test/spec/import/elements/DataInputOutputSpec.js
This shows labels for Data Input and Data Output elements.
=> Support DataInput and DataOutput labels

lib/features/modeling/BpmnUpdater.js, lib/features/rules/BpmnRules.js, test/spec/features/modeling/MoveElements.data-input-output.bpmn, test/spec/features/modeling/MoveElementsSpec.js, test/spec/features/rules/BpmnRules.dataInputOutput.collaboration.bpmn, test/spec/features/rules/BpmnRules.dataInputOutput.process.bpmn, test/spec/features/rules/BpmnRulesSpec.js, test/spec/features/rules/Helper.js, test/spec/import/elements/DataInputOutput.bpmn
Closes #961
__Improvements__
* Don't blow up on programmed DataInput / DataOutput move (https://github.com/bpmn-io/bpmn-js/commit/5e086121cc8cc5047976fa2097f3ac411752af49)
* Ensure DataInput / DataOutput may be moved within participant (https://github.com/bpmn-io/bpmn-js/commit/6ea4c555b3e1f95a52820c609464faa648f6c38e)
* Implement basic move of DataInput / DataOutput within container (`ioSpecification` holder) (https://github.com/bpmn-io/bpmn-js/commit/c77ba3a1f806edb264f19648fdf21f603a2e7d4c)
=> 961 data input output move

lib/features/modeling/BpmnUpdater.js, package-lock.json, package.json, test/spec/features/modeling/BpmnUpdaterSpec.js, test/spec/features/modeling/DeleteShape.cropping.bpmn, test/spec/features/modeling/DeleteShapeSpec.js, test/spec/features/modeling/LabelLayoutingSpec.js, test/spec/features/modeling/behavior/DropOnFlowBehaviorSpec.js, test/spec/features/modeling/behavior/RemoveElementBehavior.diagonal.bpmn, test/spec/features/modeling/behavior/RemoveElementBehaviorSpec.js
Closes #940 
Requires https://github.com/bpmn-io/diagram-js/pull/317
=> Fix connections cropping on element removal

.travis.yml, lib/Modeler.js, tasks/wiredeps
Depends on https://github.com/bpmn-io/diagram-js/pull/316.
Related to https://github.com/camunda/camunda-modeler/issues/1019.
Related to https://github.com/bpmn-io/bpmn-js/issues/973.
=> 1019 Add Snap-to-Grid

lib/Viewer.js, test/spec/ViewerSpec.js
=> fix(Viewer): remove elements di binding on clear call

lib/features/modeling/BpmnUpdater.js, lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js, lib/features/modeling/behavior/LabelBehavior.js, test/spec/features/modeling/LabelLayoutingSpec.js, test/spec/features/modeling/behavior/RemoveElementBehaviorSpec.js, test/spec/features/modeling/layout/LayoutConnectionSpec.js, test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js
Test adjustments according to https://github.com/bpmn-io/diagram-js/pull/320
Requires https://github.com/bpmn-io/diagram-js/pull/320
Closes #718
=> 718 properly layout on reconnect

lib/features/modeling/BpmnLayouter.js, test/spec/features/modeling/layout/LayoutSequenceFlowSpec.boundaryEvents.bpmn, test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js
=> 891 properly layout boundary event connection

CHANGELOG.md
_Which issue does this PR address?_
Closes #
=> chore(CHANGELOG): update to v3.4.0

lib/features/auto-place/AutoPlace.js, lib/features/auto-place/AutoPlaceUtil.js, lib/features/grid-snapping/behavior/AutoPlaceBehavior.js, lib/features/grid-snapping/behavior/index.js, lib/features/grid-snapping/index.js, test/spec/features/grid-snapping/behavior/AutoPlaceBehavior.bpmn, test/spec/features/grid-snapping/behavior/AutoPlaceBehaviorSpec.js
* move helper function to util
* integrate grid snapping with auto place feature
Depends on bpmn-io/diagram-js#322.
Closes #1003.
=> Integrate Grid Snapping with Auto Place Feature

lib/features/grid-snapping/behavior/LayoutConnectionBehavior.js, lib/features/grid-snapping/behavior/index.js, test/spec/features/grid-snapping/behavior/LayoutConnectionBehavior.bpmn, test/spec/features/grid-snapping/behavior/LayoutConnectionBehaviorSpec.js
=> Integrate Grid Snapping With Connection Layout

lib/Modeler.js, lib/features/connect/BpmnConnectPreview.js, lib/features/connect/index.js, lib/features/create/BpmnCreateConnectPreview.js, lib/features/create/index.js, test/spec/features/modeling/layout/LayoutConnectionSpec.js
Depends on https://github.com/bpmn-io/diagram-js/pull/335.
=> Connection preview fix

lib/features/auto-resize/BpmnAutoResize.js, test/spec/features/grid-snapping/behavior/AutoResizeBehavior.bpmn, test/spec/features/grid-snapping/behavior/AutoResizeBehaviorSpec.js
Requires https://github.com/bpmn-io/diagram-js/pull/333.
=> chore(bpmn-auto-resize): add test

lib/features/snapping/BpmnSnapping.js, test/spec/features/snapping/BpmnSnapping.general.bpmn, test/spec/features/snapping/BpmnSnappingSpec.js
=> feat(bpmn-snapping): snap shape to itself

test/spec/features/modeling/behavior/SubProcessBehaviorSpec.js
=> test(modeling/behavior): remove unnecessary sinon usage

lib/features/rules/BpmnRules.js, test/spec/features/rules/BpmnRules.connectOnCreate.bpmn, test/spec/features/rules/BpmnRulesSpec.js
=> fix(rules): do not allow message flows to outside diagram shapes

lib/features/grid-snapping/behavior/LayoutConnectionBehavior.js, test/spec/features/grid-snapping/behavior/LayoutConnectionBehaviorSpec.js
=> fix(layout-connection-behavior): do NOT snap on reconnect start and end

lib/features/rules/BpmnRules.js, test/spec/features/modeling/layout/LayoutConnectionSpec.js
Closes #1048
Depends on https://github.com/bpmn-io/diagram-js/pull/346
=> fix(bpmn-rules): correctly evaluate waypoints update rule

lib/features/modeling/behavior/DetachEventBehavior.js, lib/features/modeling/behavior/index.js, lib/features/rules/BpmnRules.js, test/spec/features/modeling/MoveRulesSpec.js, test/spec/features/modeling/behavior/CreateBoundaryEventBehaviorSpec.js, test/spec/features/modeling/behavior/DetachEventBehaviorSpec.js, test/spec/features/replace/BpmnReplaceSpec.js, test/spec/features/rules/BpmnRules.detaching.bpmn, test/spec/features/rules/BpmnRulesSpec.js
Closes #1045
Requires https://github.com/bpmn-io/diagram-js/pull/354
=> 1045 boundary events are dettachable

lib/features/grid-snapping/behavior/CreateParticipantBehavior.js, lib/features/grid-snapping/behavior/index.js, lib/features/modeling/behavior/CreateParticipantBehavior.js, test/spec/features/grid-snapping/behavior/CreateParticipantBehavior.bpmn, test/spec/features/grid-snapping/behavior/CreateParticipantBehaviorSpec.js
This only snaps width and height, not the position which would require way too much effort right now.
Closes #1061
=> feat(grid-snapping): snap width and height on create first participant

lib/features/modeling/behavior/ReplaceConnectionBehavior.js, test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js, test/spec/features/modeling/layout/LayoutConnectionSpec.js
=> Correctly layout and select replaced connection during reconnection

test/spec/features/modeling/behavior/ReplaceConnectionBehavior.association.bpmn, test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js
=> test(modeling): ensure reconnecting data association works

lib/features/label-editing/LabelEditingProvider.js, lib/features/modeling/ElementFactory.js
Adds automatic label editing on group creation + updates group to reasonable size:
=> Group group group

lib/features/grid-snapping/behavior/LayoutConnectionBehavior.js, test/spec/features/grid-snapping/behavior/LayoutConnectionBehavior.bpmn, test/spec/features/grid-snapping/behavior/LayoutConnectionBehaviorSpec.js
* make side-effect free
* use Modeling#updateWaypoints for actual update
Closes #1082
=> fix(grid-snapping): correctly update snapped waypoints

lib/features/snapping/BpmnCreateMoveSnapping.js, test/spec/features/snapping/BpmnCreateMoveSnapping.docking-points.bpmn, test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js
=> fix(snapping): snap to docking points

lib/Viewer.js, test/spec/ViewerSpec.js
Cf. https://github.com/bpmn-io/bpmn-js/pull/1111 for reference.
=> Restore import definitions

lib/features/modeling/BpmnUpdater.js, lib/features/modeling/behavior/ReplaceConnectionBehavior.js, test/spec/features/modeling/behavior/ReplaceConnectionBehavior.message-sequence-flow.bpmn, test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js
=> 1072 sequence flow has wrong parent after replacement

test/spec/features/modeling/lanes/AddLaneSpec.js, test/spec/features/modeling/lanes/participant-single-lane.bpmn
Related to #1129 
Related to https://github.com/bpmn-io/bpmn-js/issues/746
=> fix(graphics-factory): add test case verifying fix

package-lock.json, package.json
Uses latest bpmn-moddle release.
=> chore(project): bump bpmn-moddle version

lib/features/palette/PaletteProvider.js
=> fix(palette): add translation support for group entry

lib/features/copy-paste/BpmnCopyPaste.js, test/spec/features/copy-paste/BpmnCopyPasteSpec.js
=> fix(copy-paste): copy name property

package-lock.json, package.json, test/spec/features/grid-snapping/BpmnGridSnappingSpec.js, test/spec/features/grid-snapping/basic.bpmn
=> test(grid-snapping): verify start event mid snapping

lib/features/label-editing/LabelEditingProvider.js, test/spec/features/label-editing/LabelEditingProviderSpec.js
=> fix(label-editing): prevent direct editing after create

lib/features/rules/BpmnRules.js, package-lock.json, package.json, test/spec/features/rules/BpmnRulesSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/1462
=> Allow to create attachments

lib/import/BpmnTreeWalker.js, test/spec/import/elements/AssociationSpec.data-association.bpmn, test/spec/import/elements/AssociationSpec.js
Handle Data Associations for Boundary Events on import.
Closes #1170
=> fix(import): handle data associations on boundary import

lib/features/modeling/BpmnLayouter.js, test/spec/features/modeling/layout/LayoutSequenceFlowSpec.flowElements.bpmn, test/spec/features/modeling/layout/LayoutSequenceFlowSpec.js
Requires https://github.com/bpmn-io/diagram-js/pull/401
Closes #1121
=> fix(bpmn-layouter): get preferred layout from orientation

CHANGELOG.md, lib/features/modeling/behavior/DropOnFlowBehavior.js, test/spec/features/modeling/behavior/DropOnFlowBehaviorSpec.js
* take into account that shapes can be created with position OR bounds
Fixes #1178
=> fix(drop-on-flow-behavior): handle shape created with bounds

lib/features/copy-paste/BpmnCopyPaste.js, test/spec/features/copy-paste/BpmnCopyPasteSpec.js, test/spec/features/copy-paste/data-associations.bpmn
=> fix(copy-paste): copy process properties

test/spec/features/keyboard-move-selection/KeyboardMoveSelectionSpec.js, test/spec/features/keyboard-move-selection/keyboard-move-selection.bpmn
Requires https://github.com/bpmn-io/diagram-js/pull/409
Closes #943
=> fix(keyboard-move-selection): ensure moving lanes is not possible

lib/features/snapping/BpmnConnectSnapping.js, test/spec/features/snapping/BpmnConnectSnapping.bpmn, test/spec/features/snapping/BpmnConnectSnappingSpec.js
The problem/solution is explained inside [this comment](https://github.com/camunda/camunda-modeler/issues/1436#issuecomment-529861783) of the issue.
Related to https://github.com/camunda/camunda-modeler/issues/1436
=> fix(snapping): center detection

lib/Viewer.js, test/spec/ViewerSpec.js
=>  Do Not Clear Diagram If No Diagram to Clear

lib/features/copy-paste/BpmnCopyPaste.js, test/spec/features/copy-paste/BpmnCopyPasteSpec.js
=> fix(copy-paste): copy boundary event attachments

lib/features/modeling/behavior/DetachEventBehavior.js, lib/features/rules/BpmnRules.js, test/spec/features/copy-paste/BpmnCopyPasteSpec.js, test/spec/features/modeling/behavior/DetachEventBehaviorSpec.js, test/spec/features/rules/BpmnRulesSpec.js
Closes #1154
Requires https://github.com/bpmn-io/diagram-js/pull/410
=> feat(features): copy non attached boundary events as well

lib/features/modeling/BpmnUpdater.js, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
=> fix(modeling): "Timer Intermediate Catch Event" removes "conditionExpression" from sequence flows

lib/features/modeling/BpmnUpdater.js, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
=> fix(modeling): "Timer Intermediate Catch Event" removes "default" attribute from exclusive gateways

lib/features/modeling/behavior/DetachEventBehavior.js, lib/features/replace/BpmnReplace.js, test/spec/features/modeling/behavior/DetachEventBehaviorSpec.js
=> fix(DetachEventBehavior): allow batch detach on elements.move

lib/features/modeling/behavior/CreateBoundaryEventBehavior.js, lib/features/snapping/BpmnCreateMoveSnapping.js, test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js
=> Allow to attach shapes with labels on paste

test/spec/features/modeling/behavior/CreateBoundaryEventBehaviorSpec.js
=> Preserve properties after pasting as boundary event

lib/features/modeling/cmd/UpdateFlowNodeRefsHandler.js, test/spec/features/modeling/lanes/UpdateFlowNodeRefsSpec.js, test/spec/features/modeling/lanes/flowNodeRefs.bpmn
See [this comment](https://github.com/camunda/camunda-modeler/issues/1504#issuecomment-538992629)
Required by https://github.com/camunda/camunda-modeler/issues/1504
=> fix(modeling): provide unique hash key for flow nodes when updating

lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js, test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehaviorSpec.js
=> fix(modeling): AdaptiveLabelPositioningBehavior of labels before creation

lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js, test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehaviorSpec.js
=> Adjust Label Position When Creating Multiple Elements

package-lock.json, package.json
=> chore(project): bump diagram-js version

CHANGELOG.md
=> chore(CHANGELOG): update to 5.1.0

lib/features/popup-menu/ReplaceMenuProvider.js, test/spec/features/popup-menu/ReplaceMenuProvider.collapsedSubProcess.bpmn, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
Requires bpmn-io/diagram-js#432
Closes #1231
=> fix(replace): do not resize on replace sub process with ad hoc

test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
This further simplifies the test cases you've previously been working on.
=> test(popup-menu): further simplify ReplaceMenuProviderSpec

lib/features/modeling/behavior/AssociationBehavior.js, lib/features/modeling/behavior/index.js, test/spec/features/modeling/behavior/AssociationBehavior.bpmn, test/spec/features/modeling/behavior/AssociationBehaviorSpec.js
=> fix(modeling): update association parent on source or target move

test/spec/features/copy-paste/BpmnCopyPasteSpec.js
This PR adds a failing test case verifying #798. The failing test case was probably removed during a refactoring.
=> chore(copy-paste): add failing test case verifying #798

lib/features/modeling/ElementFactory.js, test/spec/features/modeling/ElementFactory.bpmn, test/spec/features/modeling/ElementFactorySpec.js
* use BPMN factory to create elements thus ensuring IDs
Closes #1162
=> fix(element-factory): use BPMN factory to ensure IDs

lib/draw/BpmnRenderer.js, test/spec/draw/BpmnRenderer.group-colors.bpmn, test/spec/draw/BpmnRendererSpec.js
Required by https://github.com/camunda/camunda-modeler/issues/1598
=> Color BPMN group

lib/features/modeling/behavior/FixHoverBehavior.js, test/spec/features/modeling/behavior/FixHoverBehaviorSpec.js
=> fix(modeling): correctly fix hover on cleanup, too

lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js, lib/features/modeling/behavior/LabelBehavior.js, test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehavior.basics.bpmn, test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehaviorSpec.js, test/spec/features/modeling/behavior/LabelBehaviorSpec.js
Related to camunda/camunda-modeler#1617
=> fix(adaptive-label-positioning): do not adjust on paste

test/spec/.eslintrc, test/spec/ViewerSpec.js, test/spec/features/auto-place/AutoPlaceSpec.js, test/spec/features/copy-paste/BpmnCopyPasteSpec.js, test/spec/features/copy-paste/complex.bpmn, test/spec/features/keyboard/BpmnKeyboardBindingsSpec.js, test/spec/features/modeling/BpmnUpdaterSpec.js, test/spec/features/modeling/LabelBoundsSpec.js, test/spec/features/modeling/behavior/AdaptiveLabelPositioningBehaviorSpec.js, test/spec/features/modeling/behavior/AttachEventBehaviorSpec.js, test/spec/features/modeling/behavior/DataStoreBehaviorSpec.js, test/spec/features/modeling/behavior/DetachEventBehaviorSpec.js, test/spec/features/modeling/behavior/FixHoverBehaviorSpec.js, test/spec/features/modeling/behavior/LabelBehaviorSpec.js, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js, test/spec/import/BpmnTreeWalkerSpec.js
Builds on top of https://github.com/bpmn-io/diagram-js/pull/436.
=> Consistent mark as changed

lib/features/context-pad/ContextPadProvider.js
This PR integrates translation module into 'Append ReceiveTask' action.
=> Translate title for 'Append ReceiveTask' action

CHANGELOG.md, lib/features/snapping/BpmnCreateMoveSnapping.js, package-lock.json, package.json, test/spec/features/replace/BpmnReplace.collaboration.bpmn, test/spec/features/replace/BpmnReplaceSpec.js, test/spec/features/snapping/BpmnCreateMoveSnapping.docking-create-mode.bpmn, test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js
Depends on https://github.com/bpmn-io/diagram-js/pull/439
=> Verify anchors are updated when replace changes element bounds

lib/features/modeling/behavior/DropOnFlowBehavior.js, test/spec/features/modeling/behavior/DropOnFlowBehavior.bpmn, test/spec/features/modeling/behavior/DropOnFlowBehaviorSpec.js
Closes https://github.com/bpmn-io/bpmn-js/issues/1263
=> fix(modeling/DropOnFlowBehavior): keep non-duplicate outgoing connection

lib/features/modeling/behavior/RootElementReferenceBehavior.js, test/spec/features/modeling/behavior/RootElementReferenceBehaviorSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/1639
=> fix(modeling/copy-paste): copy referenced message if not present

lib/features/modeling/behavior/RootElementReferenceBehavior.js, test/spec/features/modeling/behavior/RootElementReferenceBehavior.bpmn, test/spec/features/modeling/behavior/RootElementReferenceBehaviorSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/1637
=> Copy message referenced by receive and send task

.travis.yml
=> Update examples and websites on stable release only

lib/features/modeling/behavior/LabelBehavior.js, lib/features/modeling/behavior/ResizeBehavior.js, lib/features/modeling/behavior/SpaceToolBehavior.js, lib/features/modeling/behavior/index.js, test/matchers/BoundsMatchers.js, test/matchers/ConnectionMatchers.js, test/spec/features/modeling/LabelLayoutingSpec.js, test/spec/features/modeling/SpaceTool.basic.bpmn, test/spec/features/modeling/SpaceTool.case1.bpmn, test/spec/features/modeling/SpaceToolSpec.js, test/spec/features/modeling/behavior/LabelBehavior.bpmn, test/spec/features/modeling/behavior/LabelBehaviorSpec.js, test/spec/features/modeling/behavior/SpaceToolBehaviorSpec.bpmn, test/spec/features/modeling/behavior/SpaceToolBehaviorSpec.js
Requires https://github.com/bpmn-io/diagram-js/pull/364.
=> feat(space-tool): ensure minimum size when resizing shapes

lib/features/modeling/BpmnFactory.js, test/spec/features/modeling/BpmnFactorySpec.js
=> Assign id prefix matching element type

lib/features/modeling/cmd/AddLaneHandler.js, test/spec/features/modeling/lanes/AddLaneSpec.js, test/spec/features/modeling/lanes/lanes-flow-nodes.bpmn
Related to https://github.com/camunda/camunda-modeler/issues/1715
=> fix(modeling): update AddLaneHandler to new spaceTool API

package-lock.json, package.json
=> chore(project): update diagram-js to v6.5.0

lib/BaseModeler.js, lib/BaseViewer.js, lib/Modeler.js, lib/Viewer.js, lib/draw/PathMap.js, lib/draw/TextRenderer.js, lib/features/auto-place/AutoPlaceUtil.js, lib/features/context-pad/ContextPadProvider.js, lib/features/keyboard/BpmnKeyboardBindings.js, lib/features/label-editing/cmd/UpdateLabelHandler.js, lib/features/modeling/ElementFactory.js, lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js, lib/features/modeling/behavior/GroupBehavior.js, lib/features/modeling/behavior/util/LineAttachmentUtil.js, lib/features/modeling/util/ModelingUtil.js, lib/features/popup-menu/util/TypeUtil.js, lib/features/rules/BpmnRules.js, lib/features/search/BpmnSearchProvider.js, lib/import/BpmnTreeWalker.js, lib/util/LabelUtil.js, lib/util/ModelUtil.js, test/helper/index.js, test/integration/custom-elements/CustomElementFactory.js, test/spec/draw/BpmnRendererSpec.js, test/spec/features/copy-paste/BpmnCopyPasteSpec.js, test/util/KeyEvents.js
* replace {Boolean} with {boolean}
* replace {Number} with {number}
* replace {String} with {string}
=> chore(documentation): fix JSDoc types

CHANGELOG.md, package-lock.json, package.json, test/fixtures/bpmn/import/data-store.outside-participant.dangling.bpmn
This updates `bpmn-moddle` and adjusts a broken diagram.
=> Bump bpmn moddle

package-lock.json, package.json
Closes https://github.com/bpmn-io/bpmn-js/issues/1310
=> chore(project): bump bpmn-moddle

.eslintrc, README.md, lib/BaseModeler.js, lib/BaseViewer.js, lib/Modeler.js, lib/import/Importer.js, lib/util/CompatibilityUtil.js, package-lock.json, package.json, test/config/karma.distro.js, test/config/karma.unit.js, test/helper/index.js, test/integration/ReimportSpec.js, test/integration/SimpleModelingSpec.js, test/integration/model/BpmnModdleSpec.js, test/spec/ModelerSpec.js, test/spec/NavigatedViewerSpec.js, test/spec/ViewerSpec.js, test/spec/draw/BpmnRendererSpec.js, test/spec/features/label-editing/TouchIntegrationSpec.js, test/spec/features/modeling/LabelBoundsSpec.js, test/spec/features/ordering/BpmnDiOrderingSpec.js, test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js, test/spec/import/BpmnTreeWalkerSpec.js, test/spec/import/ImporterSpec.js, test/spec/import/elements/AssociationSpec.js, test/spec/import/elements/DataInputOutputSpec.js, test/spec/import/elements/GroupsSpec.js, test/spec/import/elements/LabelSpec.js
This PR promisifies the following APIs:
BaseViewer#importXML
BaseViewer#importDefinitions
BaseViewer#open
BaseViewer#saveXML
BaseViewer#saveSVG
Modeler#createDiagram
Tests are also promisifed.
We should have a documentation here: https://bpmn.io/l/moving-to-promises.html
----
Child of #812
=> APIs promisified

lib/features/context-pad/ContextPadProvider.js, lib/features/rules/BpmnRules.js, test/spec/features/context-pad/ContextPad.activation.bpmn, test/spec/features/context-pad/ContextPadProviderSpec.js, test/spec/features/rules/BpmnRules.process.bpmn, test/spec/features/rules/BpmnRulesSpec.js
=> Allow Text Annotations for Groups

CHANGELOG.md
=> chore(CHANGELOG): update to v7.2.1

package.json
=> Build and test distro after version bump

lib/features/modeling/Modeling.js, lib/features/modeling/cmd/UpdateDataObjectHandler.js, lib/features/popup-menu/ReplaceMenuProvider.js, test/fixtures/bpmn/features/replace/data-object.bpmn, test/spec/features/context-pad/ContextPadProviderSpec.js, test/spec/features/modeling/UpdateDataObject.bpmn, test/spec/features/modeling/UpdateDataObjectSpec.js, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
=> Add toggle to mark a dataObject as a collection

lib/draw/BpmnRenderer.js, lib/draw/PathMap.js
=> Adjust collection marker's svg path to align with parallel marker

.github/CONTRIBUTING.md
This PR aims at providing some documentation which can be used as a reference when writing tests in all our libararies.
=> chore(CONTRIBUTING): document unit test formal structuring guidance

lib/draw/BpmnRenderer.js, lib/features/popup-menu/ReplaceMenuProvider.js, test/fixtures/bpmn/features/replace/participants.bpmn, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
=> Add multiplicity marker to replace menu for participants

CHANGELOG.md, package-lock.json, package.json
* Update to diagram-js@7.0.0-beta.0
* Update changelog to latest release
=> Prepare v8.0.0 release

lib/features/popup-menu/ReplaceMenuProvider.js, test/fixtures/bpmn/features/replace/cancel-events.bpmn, test/spec/features/context-pad/ContextPadProviderSpec.js, test/spec/features/modeling/behavior/ReplaceElementBehaviourSpec.js, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
closes camunda/camunda-modeler#2026
=> Fix cancel boundary events only on transactions

.github/workflows/CI.yml, .travis.yml, tasks/stages/update-examples, tasks/stages/update-integration-test, tasks/stages/update-website, tasks/wiredeps, tasks/wiredeps_github
This adds a GitHub actions CI pipeline to our build.
=> chore: create basic GitHub action CI

.github/workflows/CI.yml, CHANGELOG.md, package-lock.json, package.json
Closes https://github.com/bpmn-io/bpmn-js/issues/1380
=> Update to diagram-js@7.2.0

README.md
Related to bpmn-io/internal-docs#196
=> chore(project): add explicit link to code of conduct

package-lock.json, package.json
Closes https://github.com/bpmn-io/bpmn-js/issues/1387
=> deps: update to diagram-js@7.2.1

package-lock.json, package.json, test/spec/features/editor-actions/BpmnEditorActionsSpec.js
Depends on https://github.com/bpmn-io/diagram-js/pull/537.
=> Test align and distribute editor actions

CHANGELOG.md
=> chore(CHANGELOG): update to v8.3.0

lib/features/modeling/behavior/ReplaceElementBehaviour.js, test/spec/features/modeling/behavior/ReplaceElementBehaviourSpec.js
=> feat: replace elements on create

lib/features/modeling/behavior/DataStoreBehavior.js, lib/features/rules/BpmnRules.js, tasks/wiredeps, test/spec/features/modeling/behavior/DataStoreBehavior.empty-pool.bpmn, test/spec/features/modeling/behavior/DataStoreBehaviorSpec.js, test/spec/features/rules/BpmnRules.collaboration-empty.bpmn, test/spec/features/rules/BpmnRulesSpec.js
=> Append DataStoreReference to first available process and disallow action if there are none

package-lock.json, package.json, test/spec/features/rules/BpmnRules.collaboration.bpmn, test/spec/features/rules/BpmnRulesSpec.js
=> deps: update bpmn-moddle to v7.1.2

lib/import/BpmnTreeWalker.js, test/spec/import/BpmnTreeWalkerSpec.js
=> fix(importer): pass context during collaboration import

package-lock.json, package.json
=> deps: bump to diagram@7.6.1

lib/draw/BpmnRenderer.js
This reverts #1515
closes #1527
=> revert(bpmnRender): remove passing attrs for rendering

lib/features/modeling/BpmnFactory.js, test/spec/features/modeling/AppendShapeSpec.js
Shall be merged into `develop`, as `master` / released changes are not affected.
----
Closes https://github.com/bpmn-io/bpmn-js/issues/1544
=> fix: don't create illegal `waypoint` property

lib/features/drilldown/DrilldownCentering.js, lib/features/drilldown/DrilldownOverlays.js, lib/features/modeling/cmd/UpdateCanvasRootHandler.js, lib/features/modeling/util/ModelingUtil.js, lib/import/BpmnImporter.js, lib/import/Importer.js, lib/util/ModelUtil.js, package-lock.json, package.json, test/spec/features/drilldown/DrilldownSpec.js, test/spec/import/ImporterSpec.js, test/spec/import/elements/CollapsedSpec.js, test/spec/util/ModelUtilSpec.js
Related to https://github.com/bpmn-io/diagram-js/pull/601.
=> Use multi-root aware diagram-js

package-lock.json, package.json
=> deps: bump to diagram-js@8.0.1

lib/features/drilldown/DrilldownBreadcrumbs.js, test/spec/features/drilldown/DrilldownSpec.js, test/spec/features/drilldown/collaboration-subprocesses.bpmn
=> fix(drilldown): allow navigation to root collaboration

CHANGELOG.md, lib/features/label-editing/LabelEditingProvider.js, lib/features/modeling/BpmnFactory.js, lib/features/modeling/cmd/SetColorHandler.js, lib/features/palette/PaletteProvider.js, package-lock.json, package.json, tasks/wiredeps, test/spec/features/label-editing/LabelEditingProviderSpec.js, test/spec/features/modeling/AppendShapeSpec.js, test/spec/features/modeling/SetColor.bpmn, test/spec/features/modeling/SetColorSpec.js, test/spec/features/palette/PaletteProviderSpec.js
This backports a couple of fixes to the `8.x` series of our library and prepares a 8.9.0 release.
=> Backport fixes to `8.x`

lib/features/popup-menu/ReplaceMenuProvider.js, test/fixtures/bpmn/features/replace/data-stores-positioned-against-participant.bpmn, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
=> fix(replace menu): prevent morphing data stores outside participants

lib/features/label-editing/cmd/UpdateLabelHandler.js, test/spec/features/modeling/UpdateLabel.bpmn, test/spec/features/modeling/UpdateLabelSpec.js
=> fix(modeling): ensure di for embedded labels

lib/features/drilldown/DrilldownBreadcrumbs.js, lib/features/drilldown/DrilldownOverlayBehavior.js, lib/features/modeling/behavior/SubProcessPlaneBehavior.js, lib/util/DrilldownUtil.js, test/spec/features/drilldown/DrilldownIntegrationSpec.js, test/spec/features/modeling/behavior/SubProcessPlaneBehaviorSpec.js
- Update Breadcrumbs when changing Names
- Ensure link between `id` <-> `id + '_plane'` always matches
=> Handle rename of plane when inside the plane

lib/features/modeling/behavior/SubProcessPlaneBehavior.js, package-lock.json, package.json, test/spec/features/modeling/behavior/SubProcessBehavior.copy-paste.bpmn, test/spec/features/modeling/behavior/SubProcessPlaneBehaviorSpec.js
closes #1556
During Copy/Paste, we handle the subprocess as if it is on a single plane. When Pasting, the children are then moved to the correct new planes.
=> feat(copy-paste): allow copy of subprocess planes

lib/features/ordering/BpmnOrderingProvider.js, test/spec/ModelerSpec.js, test/spec/features/ordering/BpmnOrderingProviderSpec.js, test/spec/features/ordering/collapsed-subprocess.bpmn, test/spec/features/ordering/data-association.bpmn
related to https://github.com/camunda/camunda-modeler/issues/2751, https://github.com/camunda/camunda-modeler/issues/2752
closes #1601, #1602
=> fix(ordering): allow groups and associations in subprocesses

lib/features/label-editing/LabelEditingProvider.js, test/spec/features/label-editing/LabelEditing.bpmn, test/spec/features/label-editing/LabelEditingProviderSpec.js
=> fix(label-editing): submit change on drilldown navigation

lib/features/ordering/BpmnOrderingProvider.js, test/spec/features/modeling/behavior/ToggleElementCollapseBehaviour.bpmn, test/spec/features/modeling/behavior/ToggleElementCollapseBehaviourSpec.js
=> fix(ordering): use specified parent when moving labels

lib/features/drilldown/DrilldownOverlayBehavior.js, test/fixtures/bpmn/collapsed-sub-process.bpmn, test/spec/ModelerSpec.js
=> fix(drilldown): create overlays on `viewer.open`

lib/features/popup-menu/ReplaceMenuProvider.js, test/fixtures/bpmn/draw/activity-markers-simple.bpmn, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
=> fix(replace): persist multi-instance props with `isSequential` change

CHANGELOG.md, lib/features/modeling/behavior/SubProcessStartEventBehavior.js, lib/features/popup-menu/ReplaceMenuProvider.js, package-lock.json, tasks/stages/update-website, test/fixtures/bpmn/draw/activity-markers-simple.bpmn, test/spec/features/modeling/behavior/SubProcessBehavior.start-event.bpmn, test/spec/features/modeling/behavior/SubProcessStartEventBehaviorSpec.js, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
=> Prepare v9.0.4 release

lib/features/label-editing/LabelEditingProvider.js, test/spec/features/label-editing/LabelEditingProviderSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/2961
=> fix: complete direct editing on selection changed

lib/BaseViewer.js, lib/util/PoweredByUtil.js, package-lock.json, package.json
This PR removes all inline styles and replaces them with direct assignment to comply with CSP style-src.
closes https://github.com/bpmn-io/bpmn-js/issues/1625
=> fix: comply with style-src CSP

CHANGELOG.md
=> chore(CHANGELOG): update to v9.1.0

lib/features/modeling/cmd/SetColorHandler.js, test/fixtures/bpmn/simple.bpmn, test/spec/features/modeling/SetColorSpec.js
=> fix(setColor): set "border color" for labels

lib/features/label-editing/LabelEditingProvider.js, package-lock.json, package.json, test/spec/features/label-editing/LabelEditingProviderSpec.js
Closes https://github.com/bpmn-io/bpmn-js/issues/1664
=> fix(label-editing): cancel on element deletion

.eslintrc, lib/features/modeling/behavior/LayoutConnectionBehavior.js
Plus add lint rule to verify it.
----
Related to https://github.com/bpmn-io/diagram-js/pull/649
=> fix: use inherits-browser

.github/workflows/CI.yml
=> ci: use codecov GitHub action

CHANGELOG.md, package-lock.json, package.json
=> Bump diagram js

CHANGELOG.md
* `FIX`: check for replacement using actual target ([#1699](https://github.com/bpmn-io/bpmn-js/pull/1699))
=> chore(CHANGELOG): update to v9.3.3

lib/features/modeling/behavior/ResizeBehavior.js, lib/features/modeling/behavior/SpaceToolBehavior.js, test/spec/features/modeling/behavior/SpaceToolBehaviorSpec.group.bpmn, test/spec/features/modeling/behavior/SpaceToolBehaviorSpec.js
=> fix(modeling): ensure group min dimensions

lib/features/modeling/ElementFactory.js, test/spec/features/modeling/ElementFactorySpec.js
Ensures we do not alter input parameters. Good practice.
=> fix(modeling): do not alter attrs passed to `ElementFactory#create`

lib/features/modeling/behavior/SubProcessPlaneBehavior.js, test/spec/features/modeling/behavior/SubProcessBehavior.planes.bpmn, test/spec/features/modeling/behavior/SubProcessPlaneBehaviorSpec.js
=> fix: move labels to new plane when collapsing sub process

lib/features/replace/BpmnReplace.js, test/spec/features/replace/BpmnReplaceSpec.js
=> fix(replace): assign default size when replacing with expanded element

package-lock.json, package.json, test/config/karma.unit.js
+ drop raw-loader (replaced by webpack built-ins)
-----
Depends on https://github.com/bpmn-io/bpmn-js/pull/1722
=> Update to webpack@5

CHANGELOG.md, package-lock.json, package.json
https://github.com/bpmn-io/bpmn-js/compare/v9.3.2...clg
=> chore(CHANGELOG): update to v9.4.0

package-lock.json, package.json, test/spec/features/modeling/behavior/SubProcessPlaneBehaviorSpec.js
=> deps: update to `bpmn-moddle@7.1.3`

lib/features/modeling/cmd/SetColorHandler.js, test/spec/features/modeling/SetColor.bpmn, test/spec/features/modeling/SetColorSpec.js
=> Do not set color on elements which cannot have it

.github/workflows/CI.yml
=> Codecov action@3

package-lock.json, package.json, rollup.config.js, test/spec/features/replace-preview/BpmnReplacePreviewSpec.js, test/spec/features/space-tool/BpmnSpaceToolSpec.js
Moves to `@rollup` provided bundling plug-ins.
=> At rollup plugins

test/config/karma.unit.js, test/spec/features/replace-preview/BpmnReplacePreviewSpec.js
Ignore consistently failing test on MacOS.
---
> Restore confidence in our CI, they say. :bus:
=> test: skip failing MacOS test

lib/features/editor-actions/BpmnEditorActions.js, lib/features/keyboard/BpmnKeyboardBindings.js, package-lock.json, package.json, test/spec/ModelerSpec.js, test/spec/features/editor-actions/BpmnEditorActionsSpec.js, test/spec/features/keyboard/BpmnKeyboardBindingsSpec.js
Closes #1782 
Depends on https://github.com/bpmn-io/diagram-js/pull/719
=> Add 'replace element' keyboard binding

lib/features/create-append-anything/AppendRules.js, test/spec/features/create-append-anything/AppendRules.bpmn, test/spec/features/create-append-anything/AppendRulesSpec.js
=> fix(create-append-anything): disallow append menu for connections

CHANGELOG.md, README.md, docs/project/SETUP.md, package-lock.json, package.json
Child of https://github.com/bpmn-io/internal-docs/issues/705
=> Add `format` task and format Markdown

lib/features/create-append-anything/AppendRules.js, test/spec/features/create-append-anything/AppendRules.bpmn, test/spec/features/create-append-anything/AppendRulesSpec.js
Prevent appending to labels which currently is possible and breaks editing:
=> fix(create-append-anything): do not allow to append from label

lib/features/create-append-anything/AppendMenuProvider.js, test/spec/features/create-append-anything/AppendMenuProvider.bpmn, test/spec/features/create-append-anything/AppendMenuProviderSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/3436
=> fix(append-anything): element connection via dragstart

lib/features/label-editing/LabelEditingProvider.js, test/spec/features/label-editing/LabelEditingProviderSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/3440
=> feat(label-editing): activate direct editing on participant creation

lib/BaseModeler.d.ts, lib/BaseModeler.js, lib/BaseModeler.spec.ts, lib/BaseViewer.d.ts, lib/BaseViewer.js, lib/BaseViewer.spec.ts, lib/Modeler.d.ts, lib/Modeler.js, lib/Modeler.spec.ts, lib/NavigatedViewer.d.ts, lib/NavigatedViewer.js, lib/NavigatedViewer.spec.ts, lib/Viewer.d.ts, lib/Viewer.js, lib/Viewer.spec.ts, package-lock.json, package.json, tsconfig.json
Includes TypeScript declarations for
* `lib/*Viewer`
* `lib/*Modeler`
More will follow.
---
Related to https://github.com/bpmn-io/bpmn-js/issues/1829
=> Add TypeScript Declarations for Viewer and Modeler

CHANGELOG.md, lib/features/replace/BpmnReplace.js, package-lock.json, package.json
Depends on https://github.com/bpmn-io/diagram-js/pull/755.
=> chore(replace): remove replace logic (now supported upstream)

CHANGELOG.md, package-lock.json, package.json
=> Update to v12.0.0

lib/BaseModeler.spec.ts, lib/BaseViewer.d.ts, lib/BaseViewer.spec.ts, lib/Modeler.spec.ts, lib/NavigatedViewer.spec.ts, lib/Viewer.spec.ts
Closes https://github.com/bpmn-io/bpmn-js/issues/1882
Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/903
=> fix: make constructors open for extension

CHANGELOG.md, package-lock.json, package.json
Includes https://github.com/bpmn-io/diagram-js/pull/772
=> Update to v12.1.1

CHANGELOG.md
=> chore(CHANGELOG): update to v13.0.0

lib/model/Types.ts
=> Fix issues for clients which have enabled `verbatimModuleSyntax`

package-lock.json, package.json, tsconfig.json
* run `tsc` in `strict` mode mirroring diagram-js
* update `diagram-js` to v12.0.2
=> Types Housekeeping

CHANGELOG.md, package-lock.json, package.json
=> Update to v13.0.5

.github/workflows/POST_RELEASE.yml, tasks/stages/update-translations
This opens a PR with translations.json update as a post release job.
Closes #1399
=> ci: update translations post release

test/spec/ModelerSpec.js
Ensures these are not removed when collecting translations.
Follow-up to https://github.com/bpmn-io/bpmn-js/pull/1913
=> test: translate special strings

.github/workflows/POST_RELEASE.yml, tasks/stages/update-translations
Fixes problems from the run: https://github.com/bpmn-io/bpmn-js/actions/runs/5003230364/jobs/8964192892
=> Fix translations update

lib/draw/BpmnRenderer.js
Related to https://github.com/bpmn-io/bpmn-js/security/code-scanning/1
=> fix: improve regex

lib/features/space-tool/BpmnSpaceTool.js, package-lock.json, package.json, test/spec/features/space-tool/BpmnSpaceTool.participants.bpmn, test/spec/features/space-tool/BpmnSpaceToolSpec.js
=> fix(space-tool): prevent empty pools from getting resized vertically

package-lock.json, package.json, tasks/build-distro.mjs
Replace with maintained `cpy` utility.
=> chore: drop ancient `cpx` dependency

package-lock.json, package.json
Reverts bpmn-io/bpmn-js#1956
----
Not sure how this passed CI. It needs major changes across our shared presets (among other things).
=> Revert "chore: update dependency remark-cli to v12"

test/spec/features/modeling/behavior/DataStoreBehaviorSpec.js, test/spec/features/snapping/BpmnCreateMoveSnappingSpec.js
I just fat fingered searching for participant in the repo and noticed that there were occurrences with the same mistake :laughing:
=> chore: fix participant typo

.github/workflows/POST_RELEASE.yml, .github/workflows/RELEASE.yml
Related to https://github.com/bpmn-io/internal-docs/issues/639
=> ci: implement automated release

package-lock.json, package.json, tasks/build-distro.mjs, tasks/test-distro.mjs
=> Fix asset path

package-lock.json, package.json
feat: remove selection outline from connections (#826)
feat: position context pad according to last waypoint for connections (#826)
=> deps: update to `diagram-js@13.8.0`

package-lock.json, package.json
=> deps: update to diagram@13.1.0

.github/CONTRIBUTING.md, .github/workflows/CODE_SCANNING.yml, .github/workflows/MERGE_MAIN_TO_DEVELOP.yml, .github/workflows/RELEASE.yml, CHANGELOG.md, README.md, docs/project/SETUP.md
This prepares changing our `master` to `main` branch. To be done once this PR receives a :heavy_check_mark:
=> Use `main` branch

lib/features/modeling/behavior/CompensateBoundaryEventBehavior.js, test/spec/features/modeling/behavior/CompensateBoundaryEventBehaviorSpec.js
=> fix: support core replace in compensation behavior

lib/features/modeling/BpmnUpdater.js, test/spec/features/modeling/UpdateLabel.bpmn, test/spec/features/modeling/UpdateLabelSpec.js
=> fix: do not set label on planes

lib/draw/BpmnRenderer.js, test/spec/draw/BpmnRendererSpec.js
Closes #2085
It took me a while to find a good location for the test. I think the location I chose fits this small fix.
=> Multiple Parallel Events Fill

lib/features/interaction-events/BpmnInteractionEvents.js, test/fixtures/bpmn/collaboration-vertical.bpmn, test/spec/features/interaction-events/BpmnInteractionEventsSpec.js
Closes #2093 
Thanks to the great help by @barmac this issue can now be fixed as well.
=> Create Hit Boxes for Vertical Pools and Lanes

package-lock.json, package.json, test/spec/ModelerSpec.js, test/spec/NavigatedViewerSpec.js, test/spec/ViewerSpec.js
=> test: setup accessibility tests with axe

lib/features/context-pad/ContextPadProvider.js, lib/features/modeling/cmd/SetColorHandler.js, lib/features/modeling/cmd/SplitLaneHandler.js, lib/features/ordering/BpmnOrderingProvider.js, lib/import/BpmnTreeWalker.js, rollup.config.js, test/spec/features/ordering/Helper.js
=> fix: error info use tagged template

package-lock.json, package.json, test/spec/features/context-pad/ContextPadProviderSpec.js
Uses new context pad (no overlay, absolute position).
=> deps: update to diagram-js v14.5.1

CHANGELOG.md, package-lock.json, package.json
=> Update to diagram-js v14.5.2

CHANGELOG.md, package-lock.json, package.json
* `DEPS`: update to `diagram-js@14.6.0`
=> Update diagram js to v14.6.0

lib/features/outline/OutlineProvider.js, test/spec/features/outline/OutlineProvider.bpmn, test/spec/features/outline/OutlineProviderSpec.js
=> fix(outline): customize call activity outline

CHANGELOG.md, package-lock.json, package.json
=> deps: update to diagram-js@14.7.1

lib/features/search/BpmnSearchProvider.js, test/spec/features/search/BpmnSearchProviderSpec.js, test/spec/features/search/bpmn-search.bpmn
=> fix(search): do not suggest subprocess planes

package-lock.json, package.json, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js
fix: remove incorrect attribute in replace menu
Related to https://github.com/camunda/camunda-modeler/issues/4383
=> deps: update to `diagram-js@14.7.2`

lib/features/label-editing/LabelEditingPreview.js
The Bug
Resolution 
Related to: [#4477](https://github.com/camunda/camunda-modeler/issues/4477)
=> fix: label text visible while editing

README.md
Links awesome list directly from the repository. This allows folks to discover the wider eco-system of tools that are related to the library.
=> docs: link awesome list

package-lock.json, package.json
Closes https://github.com/bpmn-io/bpmn-js/issues/2233
=> deps: bump to diagram-js@14.11.2

.github/workflows/CI.yml, .github/workflows/CODE_SCANNING.yml, .github/workflows/MERGE_MAIN_TO_DEVELOP.yml, .github/workflows/POST_RELEASE.yml, .github/workflows/RELEASE.yml
Follows along our move to make job names `snake_case`.
Related to https://github.com/bpmn-io/diagram-js/pull/945
=> ci: adjust job names to `snake_case`

CHANGELOG.md, package-lock.json, package.json, test/spec/ModelerSpec.js
Related to https://github.com/bpmn-io/internal-docs/issues/1081
Update `diagram-js` to v15.0.0 with [breaking changes](https://github.com/bpmn-io/diagram-js/pull/662).
=> deps: update to diagram-js@15.0.0

CHANGELOG.md
Node@18 is [soon out of maintenance](https://nodejs.org/en/about/previous-releases) and I'd rather only major bump for such a change once.
=> chore: require node@20

CHANGELOG.md, package-lock.json, package.json
Related to https://github.com/bpmn-io/internal-docs/issues/1081
Update to `diagram-js-direct-editing@3.2.0`
=> deps: update to diagram-js-direct-editing@3.2.0

.github/workflows/MERGE_MAIN_TO_DEVELOP.yml
Related to https://github.com/bpmn-io/internal-docs/issues/1094
This migrates the slack integration to use the v2 API.
=> ci: migrate to slack action v2

CHANGELOG.md
* `FEAT`: add ad-hoc subprocess option to replace menu ([#2276](https://github.com/bpmn-io/bpmn-js/pull/2276))
=> chore(CHANGELOG): update to v18.2.0

.github/workflows/POST_RELEASE.yml
This is required for the translations update. Cf. https://github.com/bpmn-io/bpmn-js/actions/runs/12948699811
=> ci: setup project in post-release

test/spec/features/auto-place/BpmnAutoPlaceSpec.js, test/spec/features/copy-paste/BpmnCopyPasteSpec.js, test/spec/features/distribute-elements/BpmnDistributeElementsSpec.js, test/spec/features/label-editing/LabelEditingProviderSpec.js, test/spec/features/modeling-feedback/ModelingFeedbackSpec.js, test/spec/features/modeling/LabelBoundsSpec.js, test/spec/features/modeling/append/TextAnnotationSpec.js, test/spec/features/modeling/behavior/LabelBehaviorSpec.js, test/spec/features/modeling/behavior/LayoutConnectionBehaviorSpec.js, test/spec/features/modeling/behavior/ReconnectConnectionSpec.js, test/spec/features/modeling/behavior/ResizeBehaviorSpec.js, test/spec/features/modeling/behavior/RootElementReferenceBehaviorSpec.js, test/spec/features/modeling/behavior/SubProcessPlaneBehaviorSpec.js, test/spec/features/modeling/lanes/AddLaneSpec.js, test/spec/features/popup-menu/ReplaceMenuProviderSpec.js, test/spec/features/replace/BpmnReplaceSpec.js, test/spec/features/rules/BpmnRulesSpec.js
Consistently put two empty lines between each describe or test(it) block
=> Apply rules for consistent test spacing

.gitignore, CHANGELOG.md, package-lock.json, package.json
Incorporates https://github.com/bpmn-io/diagram-js/pull/989.
=> Update to `diagram-js@15.3.1`
